/*
 * registers.h
 *
 *  Created on: Mar 6, 2013
 *      Author: eric
 */

#ifndef REGISTERS_H_
#define REGISTERS_H_

//#include "mitr_types.h"
//
//#define FPGA_I2C_ADDR 	0x3C /* i2c address of the FPGA */
//
//typedef enum{
//	MITR_FPGA_IRIG_IN_CHANNEL_ID = 0,		//0
//	MITR_FPGA_IRIG_IN_SRC,
//	MITR_FPGA_IRIG_IN_ENABLE,
//	MITR_FPGA_IRIG_IN_SIGNAL,
//	MITR_FPGA_IRIG_IN_SRC_SEC,
//	MITR_FPGA_IRIG_IN_CURR_TIME_SRC,
//	MITR_FPGA_IRIG_IN_TIME_MSEC,
//	MITR_FPGA_IRIG_IN_TIME_SEC,
//	MITR_FPGA_IRIG_IN_TIME_MIN,
//	MITR_FPGA_IRIG_IN_TIME_HOUR,
//	MITR_FPGA_IRIG_IN_TIME_DAY,		//10
//	MITR_FPGA_IRIG_IN_TIME_TDAY,
//	MITR_FPGA_IRIG_IN_TIME_YEAR,
//	MITR_FPGA_IRIG_IN_HEALTH,
//	MITR_FPGA_IRIG_IN_RTC_LSW,
//	MITR_FPGA_IRIG_IN_RTC_DIFF_LSW,
//	MITR_FPGA_IRIG_IN_RTC_DIFF_MSW,
//	MITR_FPGA_IRIG_IN_CAL_MSB,
//	MITR_FPGA_IRIG_IN_CAL_LSB,
//	MITR_FPGA_IRIG_IN_RTC_CAL_MSB,
//	MITR_FPGA_IRIG_IN_OFFSET_MULTIPLIER,		//20
//	MITR_FPGA_IRIG_IN_GPS_SECOND_WRITE,
//	MITR_FPGA_IRIG_IN_GPS_SECOND_READ,
//	MITR_FPGA_IRIG_IN_RTC_LATCHED_LSW,
//	MITR_FPGA_IRIG_IN_RTC_LATCHED_MSW,
//	MITR_FPGA_IRIG_IN_INTERRUPT,
//	MITR_FPGA_IRIG_OUT_CHANNEL_ID,
//	MITR_FPGA_IRIG_OUT_TIMECODE,
//	MITR_FPGA_IRIG_OUT_ENABLE,
//	MITR_FPGA_IEEE_1588_MODE,
//	MITR_FPGA_IRIG_OUT_MODE,		//30
//	MITR_FPGA_TTL_1PPS_ENABLE,
//	MITR_FPGA_IRIG_OUT_HEALTH,
//	MITR_FPGA_IRIG_OUT_RTC_LSW,
//	MITR_FPGA_IRIG_OUT_RTC_MSW,
//	MITR_FPGA_IRIG_OUT_PHASE_MULT0,
//	MITR_FPGA_IRIG_OUT_PHASE_MULT1,
//	MITR_FPGA_IRIG_OUT_TCG_CAL_COARSE,
//	MITR_FPGA_IRIG_OUT_TCG_CAL_MID,
//	MITR_FPGA_IRIG_OUT_TCG_CAL_FINE_MSB,
//	MITR_FPGA_IRIG_OUT_TCG_CAL_FINE_LSB,		//40
//	MITR_FPGA_IRIG_OUT_TIME_MSEC,
//	MITR_FPGA_IRIG_OUT_TIME_SEC,
//	MITR_FPGA_IRIG_OUT_TIME_MIN,
//	MITR_FPGA_IRIG_OUT_TIME_HOUR,
//	MITR_FPGA_IRIG_OUT_TIME_DAY,
//	MITR_FPGA_DISC_IN_STATE,
//	MITR_FPGA_DISC_OUT_STATE,
//	MITR_FPGA_DISC_DEBOUNCE_TIME,
//	MITR_FPGA_LED_CONTROL_R_B,
//	MITR_FPGA_LED_CONTROL_G,		//50
//	MITR_FPGA_LED_CONTROL_FLASH,
//	MITR_FPGA_1588_TIME_MS,
//	MITR_FPGA_1588_TIME_SEC,
//	MITR_FPGA_1588_TIME_MIN,
//	MITR_FPGA_1588_TIME_HOUR,
//	MITR_FPGA_1588_TIME_DAY,
//	MITR_FPGA_1588_TIME_HDAY,
//	MITR_FPGA_1588_TIME_YEAR,
//	MITR_FPGA_1588_TIME_HEALTH,		//59
//
//	MITR_FPGA_REGISTER_END
//}mitr_registers_t;
//
//typedef struct mitr_register_info_t{
//	u8 regnum;
//	u32 mask;
//	u8 shift;
//}mitr_register_info;
//
//extern const mitr_register_info mitr_reg_info[];

#endif /* REGISTERS_H_ */
