/*
 * tsd_RTC_CALIBRATOR_registers.h
 *
 *  Created on: Sep 5, 2017
 *      Author: eric
 */

#ifndef TSD_RTC_CALIBRATOR_REGISTERS_H_
#define TSD_RTC_CALIBRATOR_REGISTERS_H_

#include <io.h>

#define TSD_RTC_CALIBRATOR_MAX_CHANNELS		(8)
/**************************************
 * RTC_CALIBRATOR DEFINES
 **************************************/
#define TSD_RTC_CALIBRATOR_CONTROL_ENABLE				(0x01) /* ENABLE/DISABLE THE MODULE */
#define TSD_RTC_CALIBRATOR_CONTROL_PID_ENABLE			(0x02) /* RUN THE PID CONTROLLER */
#define TSD_RTC_CALIBRATOR_CONTROL_100MHZ_CAL_ENABLE	(0x04) /* RUN THE 100MHZ CALIBRATOR */
#define TSD_RTC_CALIBRATOR_CONTROL_RESET				(0x80000000)


/**************************************
 * RTC_CALIBRATOR REGISTERS
 **************************************/
#define TSD_RTC_CALIBRATOR_VERSION_REG			(0x00)
#define TSD_RTC_CALIBRATOR_CONTROL_REG			(0x01)
#define TSD_RTC_CALIBRATOR_STATUS_REG			(0x02)
#define TSD_RTC_CALIBRATOR_ERROR_TICKS_REG		(0x03)
#define TSD_RTC_CALIBRATOR_CURRENT_RTC_H_REG	(0x04)
#define TSD_RTC_CALIBRATOR_CURRENT_RTC_L_REG	(0x05)
#define TSD_RTC_CALIBRATOR_LATCHED_RTC_H_REG	(0x06)
#define TSD_RTC_CALIBRATOR_LATCHED_RTC_L_REG	(0x07)

/**************************************
 * RTC_CALIBRATOR REGISTER ACCESS
 **************************************/

#define TSD_RTC_CALIBRATOR_IORD_VERSION(base)			IORD(base, TSD_RTC_CALIBRATOR_VERSION_REG)

#define TSD_RTC_CALIBRATOR_IORD_CONTROL(base)			IORD(base, TSD_RTC_CALIBRATOR_CONTROL_REG)
#define TSD_RTC_CALIBRATOR_IOWR_CONTROL(base, val)		IOWR(base, TSD_RTC_CALIBRATOR_CONTROL_REG, val)

#define TSD_RTC_CALIBRATOR_IORD_STATUS(base)			IORD(base, TSD_RTC_CALIBRATOR_STATUS_REG)

#define TSD_RTC_CALIBRATOR_IORD_ERROR_TICKS(base)		IORD(base, TSD_RTC_CALIBRATOR_ERROR_TICKS_REG)

#define TSD_RTC_CALIBRATOR_IORD_CURRENT_RTC_H(base)		IORD(base, TSD_RTC_CALIBRATOR_CURRENT_RTC_H_REG)
#define TSD_RTC_CALIBRATOR_IORD_CURRENT_RTC_L(base)		IORD(base, TSD_RTC_CALIBRATOR_CURRENT_RTC_L_REG)

#define TSD_RTC_CALIBRATOR_IORD_LATCHED_RTC_H(base)		IORD(base, TSD_RTC_CALIBRATOR_LATCHED_RTC_H_REG)
#define TSD_RTC_CALIBRATOR_IORD_LATCHED_RTC_L(base)		IORD(base, TSD_RTC_CALIBRATOR_LATCHED_RTC_L_REG)

#endif /* TSD_RTC_CALIBRATOR_REGISTERS_H_ */
