/*
 * tsd_TIME_INPUT_SELECTOR_registers.h
 *
 *  Created on: Sep 5, 2017
 *      Author: eric
 */

#ifndef TSD_TIME_INPUT_SELECTOR_REGISTERS_H_
#define TSD_TIME_INPUT_SELECTOR_REGISTERS_H_

#include <io.h>

#define TSD_TIME_INPUT_SELECTOR_MAX_CHANNELS        (8)
/**************************************
 * TIME_INPUT_SELECTOR DEFINES
 **************************************/
#define TSD_TIME_INPUT_SELECTOR_CONTROL_ENABLE        (0x01)
#define TSD_TIME_INPUT_SELECTOR_CONTROL_RESET        (0x80000000)

#define TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_LOCKED_MASK    (0x00000001)
#define TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_TYPE_MASK        (0x0000000E)
#define TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_TYPE_SHFT        (1)
#define TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_SEL_MASK        (0x00000700)
#define TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_SEL_SHFT        (8)

/* VALUES FROM TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_TYPE_MASK (AFTER MASK AND SHIFT) */
#define TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_TYPE_INTERNAL    (0x00) /* INPUT SOURCE IS FROM A MANUAL INCREMENTER */
#define TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_TYPE_IRIG        (0x01) /* INPUT SOURCE IS FROM AN IRIG SOURCE */
#define TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_TYPE_GPS        (0x02) /* INPUT SOURCE IS FROM A GPS SOURCE */
#define TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_TYPE_1PPS        (0x04) /* INPUT SOURCE IS FROM A 1PPS SOURCE */

/*
 * VALUES FROM TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_SEL_MASK (AFTER MASK AND SHIFT)
 * ALSO USED AS INPUT CHANNEL NUMBER
 */
#define TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_0                (0x00) /* INPUT 0 */
#define TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_1                (0x01) /* INPUT 1 */
#define TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_2                (0x02) /* INPUT 2 */
#define TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_3                (0x03) /* INPUT 3 */
#define TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_4                (0x04) /* INPUT 4 */
#define TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_5                (0x05) /* INPUT 5 */
#define TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_6                (0x06) /* INPUT 6 */
#define TSD_TIME_INPUT_SELECTOR_STATUS_INPUT_7                (0x07) /* INPUT 7 */

#define TSD_TIME_INPUT_SELECTOR_TIME_L_BCD_MSEC_MASK        (0x000000FF)
#define TSD_TIME_INPUT_SELECTOR_TIME_L_BCD_SECONDS_MASK        (0x0000FF00)
#define TSD_TIME_INPUT_SELECTOR_TIME_L_BCD_MINUTES_MASK        (0x00FF0000)
#define TSD_TIME_INPUT_SELECTOR_TIME_L_BCD_HOURS_MASK        (0xFF000000)

#define TSD_TIME_INPUT_SELECTOR_TIME_H_BCD_DAYS_MASK        (0x00000FFF)
#define TSD_TIME_INPUT_SELECTOR_TIME_H_BCD_YEARS_MASK        (0x00FF0000)

#define TSD_TIME_INPUT_SELECTOR_TIME_L_BCD_MSEC_RSHFT        (0)
#define TSD_TIME_INPUT_SELECTOR_TIME_L_BCD_SECONDS_RSHFT    (8)
#define TSD_TIME_INPUT_SELECTOR_TIME_L_BCD_MINUTES_RSHFT    (16)
#define TSD_TIME_INPUT_SELECTOR_TIME_L_BCD_HOURS_RSHFT        (24)

#define TSD_TIME_INPUT_SELECTOR_TIME_H_BCD_DAYS_RSHFT        (0)
#define TSD_TIME_INPUT_SELECTOR_TIME_H_BCD_HDAYS_RSHFT        (8)
#define TSD_TIME_INPUT_SELECTOR_TIME_H_BCD_YEARS_RSHFT        (16)

/**************************************
 * TIME_INPUT_SELECTOR REGISTERS
 **************************************/
#define TSD_TIME_INPUT_SELECTOR_VERSION_REG            (0x00)
#define TSD_TIME_INPUT_SELECTOR_CONTROL_REG            (0x01)
#define TSD_TIME_INPUT_SELECTOR_STATUS_REG            (0x02)
#define TSD_TIME_INPUT_SELECTOR_PRIO_REG            (0x03)
#define TSD_TIME_INPUT_SELECTOR_TIME_L_REG            (0x04)
#define TSD_TIME_INPUT_SELECTOR_TIME_H_REG            (0x05)


/**************************************
 * TIME_INPUT_SELECTOR REGISTER ACCESS
 **************************************/

#define TSD_TIME_INPUT_SELECTOR_IORD_VERSION(base)            IORD(base, TSD_TIME_INPUT_SELECTOR_VERSION_REG)

#define TSD_TIME_INPUT_SELECTOR_IORD_CONTROL(base)            IORD(base, TSD_TIME_INPUT_SELECTOR_CONTROL_REG)
#define TSD_TIME_INPUT_SELECTOR_IOWR_CONTROL(base, val)        IOWR(base, TSD_TIME_INPUT_SELECTOR_CONTROL_REG, val)

#define TSD_TIME_INPUT_SELECTOR_IORD_STATUS(base)            IORD(base, TSD_TIME_INPUT_SELECTOR_STATUS_REG)

#define TSD_TIME_INPUT_SELECTOR_IORD_PRIO(base)                IORD(base, TSD_TIME_INPUT_SELECTOR_PRIO_REG)
#define TSD_TIME_INPUT_SELECTOR_IOWR_PRIO(base, val)        IOWR(base, TSD_TIME_INPUT_SELECTOR_PRIO_REG, val)

#define TSD_TIME_INPUT_SELECTOR_IORD_TIME_L(base)            IORD(base, TSD_TIME_INPUT_SELECTOR_TIME_L_REG)

#define TSD_TIME_INPUT_SELECTOR_IORD_TIME_H(base)            IORD(base, TSD_TIME_INPUT_SELECTOR_TIME_H_REG)

#endif /* TSD_TIME_INPUT_SELECTOR_REGISTERS_H_ */
