/*
 * 
 *
 *  Created on: Oct 31, 2022
 *      Author: Jason Alden
 *      Copyright: Telspan Data 2022
 */


#ifndef VNS_FPGA_CLI_8_PORT_H_
#define VNS_FPGA_CLI_8_PORT_H_

#if defined (BOARD_VNS_8_REF)

#include "dot_command_strings.h" 

#undef DOT_CMD_STR_HELP_FUNC
#define DOT_CMD_STR_HELP_FUNC FPGA_dot_ies_8_help_cmd


#define VNS_FPGA_HELP_STRING     \
    CLI_COMMANDS_BRACKET(  DOT_CMD_STR_BIT,      DOT_CMD_STR_BIT_DESC       ) \
    CLI_COMMANDS_BRACKET(  DOT_CMD_STR_INFO,     DOT_CMD_STR_INFO_DESC      ) \
    CLI_COMMANDS_BRACKET(  DOT_CMD_STR_RESET,    DOT_CMD_STR_RESET_DESC     ) \
    CLI_COMMANDS_BRACKET(  DOT_CMD_STR_VERSION,  DOT_CMD_STR_VERSION_DESC   ) \
    CLI_COMMANDS_BRACKET(  DOT_CMD_STR_SN,       DOT_CMD_STR_SN_DESC        )



#define ADD_CLI_TAB_ENTRIES() \
        /***************************************************************************/ \
        /*                          iES DOT Commands                               */ \
        /***************************************************************************/ \
        CLI_CMD_TAB_ENTRY_MACRO( VNS_NULL,  DOT_CMD_STR_BIT_CMD,            DOT_CMD_STR_BIT_DESC,         DOT_CMD_STR_BIT_FUNC     ) \
        CLI_CMD_TAB_ENTRY_MACRO( VNS_NULL,  DOT_CMD_STR_INFO_CMD,           DOT_CMD_STR_INFO_DESC,        DOT_CMD_STR_INFO_FUNC    ) \
        CLI_CMD_TAB_ENTRY_MACRO( VNS_NULL,  DOT_CMD_STR_RESET_CMD,          DOT_CMD_STR_RESET_DESC,       DOT_CMD_STR_RESET_FUNC   ) \
        CLI_CMD_TAB_ENTRY_MACRO( VNS_NULL,  DOT_CMD_STR_VERSION_CMD,        DOT_CMD_STR_VERSION_DESC,     DOT_CMD_STR_VERSION_FUNC ) \
        CLI_CMD_TAB_ENTRY_MACRO( VNS_NULL,  DOT_CMD_STR_SN_CMD,             DOT_CMD_STR_SN_DESC,          DOT_CMD_STR_SN_FUNC      ) \
        /***************************************************************************/ \
        /*                          iES Debug Commands                             */ \
        /***************************************************************************/ \
        CLI_CMD_TAB_ENTRY_MACRO( VNS_NULL,  IES_DEBUG_CMD_STR_EPE_LIC_CMD,        IES_DEBUG_CMD_STR_EPE_LIC_DESC,     IES_DEBUG_CMD_STR_EPE_LIC_FUNC   ) \
        CLI_CMD_TAB_ENTRY_MACRO( VNS_NULL,  IES_DEBUG_CMD_STR_BRD_MDL_CMD,        IES_DEBUG_CMD_STR_BRD_MDL_DESC,     IES_DEBUG_CMD_STR_BRD_MDL_FUNC   ) \
        CLI_CMD_TAB_ENTRY_MACRO( VNS_NULL,  IES_DEBUG_CMD_STR_BRD_NUM_CMD,        IES_DEBUG_CMD_STR_BRD_NUM_DESC,     IES_DEBUG_CMD_STR_BRD_NUM_FUNC   ) \
        CLI_CMD_TAB_ENTRY_MACRO( VNS_NULL,  IES_DEBUG_CMD_STR_BRD_REV_CMD,        IES_DEBUG_CMD_STR_BRD_REV_DESC,     IES_DEBUG_CMD_STR_BRD_REV_FUNC   ) \
        CLI_CMD_TAB_ENTRY_MACRO( VNS_NULL,  IES_DEBUG_CMD_STR_BRD_ID_CMD,         IES_DEBUG_CMD_STR_BRD_ID_DESC,      IES_DEBUG_CMD_STR_BRD_ID_FUNC    ) \
        CLI_CMD_TAB_ENTRY_MACRO( VNS_NULL,  IES_DEBUG_CMD_STR_PRDT_ID_CMD,        IES_DEBUG_CMD_STR_PRDT_ID_DESC,     IES_DEBUG_CMD_STR_PRDT_ID_FUNC   ) \
        CLI_CMD_TAB_ENTRY_MACRO( VNS_NULL,  IES_DEBUG_CMD_STR_I2C_READ_CMD,       IES_DEBUG_CMD_STR_I2C_READ_DESC,    IES_DEBUG_CMD_STR_I2C_READ_FUNC  ) \
        CLI_CMD_TAB_ENTRY_MACRO( VNS_NULL,  IES_DEBUG_CMD_STR_I2C_WRITE_CMD,      IES_DEBUG_CMD_STR_I2C_WRITE_DESC,   IES_DEBUG_CMD_STR_I2C_WRITE_FUNC ) \
        CLI_CMD_TAB_ENTRY_MACRO( VNS_NULL,  IES_DEBUG_CMD_STR_DEBUG_CMD,          IES_DEBUG_CMD_STR_DEBUG_DESC,       IES_DEBUG_CMD_STR_DEBUG_FUNC     ) \
        CLI_CMD_TAB_ENTRY_MACRO( VNS_NULL,  IES_DEBUG_CMD_STR_TIMER_CMD,          IES_DEBUG_CMD_STR_TIMER_DESC,       IES_DEBUG_CMD_STR_TIMER_FUNC     ) \
        CLI_CMD_TAB_ENTRY_MACRO( VNS_NULL,  IES_DEBUG_CMD_STR_CONFIG_CMD,         IES_DEBUG_CMD_STR_CONFIG_DESC,      IES_DEBUG_CMD_STR_CONFIG_FUNC    ) \
        CLI_CMD_TAB_ENTRY_MACRO( VNS_NULL,  IES_DEBUG_CMD_STR_REGDUMP_CMD,        IES_DEBUG_CMD_STR_REGDUMP_DESC,     IES_DEBUG_CMD_STR_REGDUMP_FUNC   ) \
        CLI_CMD_TAB_ENTRY_MACRO( VNS_NULL,  IES_DEBUG_CMD_STR_EPE_PORT_CMD,       IES_DEBUG_CMD_STR_EPE_PORT_DESC,    IES_DEBUG_CMD_STR_EPE_PORT_FUNC  )

        /* CLI_CMD_TAB_ENTRY_MACRO( ((void *)0),IES_DEBUG_CMD_STR_EPE_PORT,       IES_DEBUG_CMD_STR_EPE_PORT_ARGS,  IES_DEBUG_CMD_STR_EPE_PORT_DESC,  IES_DEBUG_CMD_STR_EPE_PORT_FUNC ) */

#define DOT_CMD_STR_TIMIN_HELP_STR ""
#define DOT_CMD_STR_DISCRETE_HELP_STR ""
#define DOT_CMD_STR_DISOUT_HELP_STR ""



#else
#error "Not including help file"

#endif /* BOARD_VNS_8_REF */

#endif /* VNS_FPGA_CLI_8_PORT_H_ */
