/*

 Vitesse Switch Software.

 Copyright (c) 2002-2012 Vitesse Semiconductor Corporation "Vitesse". All
 Rights Reserved.

 Unpublished rights reserved under the copyright laws of the United States of
 America, other countries and international treaties. Permission to use, copy,
 store and modify, the software and its source code is granted. Permission to
 integrate into other products, disclose, transmit and distribute the software
 in an absolute machine readable format (e.g. HEX file) is also granted.  The
 source code of the software may not be disclosed, transmitted or distributed
 without the written permission of Vitesse. The software and its source code
 may only be used in products utilizing the Vitesse switch products.

 This copyright notice must appear in any copy, modification, disclosure,
 transmission or distribution of the software. Vitesse retains all ownership,
 copyright, trade secret and proprietary rights in the software.

 THIS SOFTWARE HAS BEEN PROVIDED "AS IS," WITHOUT EXPRESS OR IMPLIED WARRANTY
 INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 FOR A PARTICULAR USE AND NON-INFRINGEMENT.

*/
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <main.h>
#include <cyg/hal/hal_io.h>
#include <cyg/infra/cyg_type.h>
#include <sys/param.h>

#include <ucd-snmp/config.h>
#if HAVE_STDLIB_H
#include <stdlib.h>
#endif                          /* HAVE_STDLIB_H */
#if HAVE_STRING_H
#include <string.h>
#else
#include <strings.h>
#endif                          /* HAVE_STRING_H */

#include <ucd-snmp/mibincl.h>   /* Standard set of SNMP includes */
#include "ieee8021BridgeMib.h"


#define VTSS_TRACE_MODULE_ID VTSS_MODULE_ID_SNMP
#define SNMP_ASN_OCTET_STR_MAX_LEN  64 /* FIXME : Re-define it if needed */

#include "mgmt_api.h"
#include "misc_api.h" //iport2uport()
#include "ifIndex_api.h"
#include "dot1Port_api.h"
#include "mstp_api.h"

#define IEEE8021BRIDGECOMPONENTID 1
#define IEEE8021BRIDGECOMPONENT_CNT 1


/*
 *
 * * The entry data structure for ieee8021BridgeBasePortTable
 */
typedef struct {

    /*
     * Entry keys
     */
    u_long ieee8021BridgeBasePortComponentId;
    u_long ieee8021BridgeBasePort;

    /*
     * Entry columns
     */
    long            ieee8021BridgeBasePortIfIndex;
    struct counter64
            ieee8021BridgeBasePortDelayExceededDiscards;
    struct counter64
            ieee8021BridgeBasePortMtuExceededDiscards;
    char
    ieee8021BridgeBasePortCapabilities[SNMP_ASN_OCTET_STR_MAX_LEN];
    size_t ieee8021BridgeBasePortCapabilities_len;
    char
    ieee8021BridgeBasePortTypeCapabilities[SNMP_ASN_OCTET_STR_MAX_LEN];
    size_t ieee8021BridgeBasePortTypeCapabilities_len;
    long ieee8021BridgeBasePortType;
    long ieee8021BridgeBasePortExternal;
    long ieee8021BridgeBasePortAdminPointToPoint;
    long ieee8021BridgeBasePortOperPointToPoint;
    char ieee8021BridgeBasePortName[SNMP_ASN_OCTET_STR_MAX_LEN];
    size_t ieee8021BridgeBasePortName_len;
} ieee8021BridgeBasePortTable_entry_t;


/*
 * The return data structure
 */
typedef struct {
    long            long_ret;
    char            string_ret[SNMP_ASN_OCTET_STR_MAX_LEN];
    struct counter64 c64_ret;
    u_long          ulong_ret;
} ieee8021BridgeMib_return_t;

/*
 * The UCD-SNMP engine need a address point for processing get opertion
 */
/*lint -esym(459, ieee8021BridgeMib_global_ret) */ /* Process one packet at the same time, therefore unprotected access is acceptable */
static ieee8021BridgeMib_return_t ieee8021BridgeMib_global_ret;       /* static variables for retuning */

/*
 *
 * * ieee8021BridgeBasePortTable_variables_oid:
 * *   this is the top level oid that we want to register under.  This
 * *   is essentially a prefix, with the suffix appearing in the
 * *   variable below.
 */
oid ieee8021BridgeBasePortTable_variables_oid[] = {
    1, 3, 111, 2, 802, 1, 1, 2, 1, 1, 4
};


/*
 *
 * * variable ieee8021BridgeBasePortTable_variables:
 * *   this variable defines function callbacks and type return information
 * *   for the ieee8021BridgeBasePortTable mib section
 */
struct variable2 ieee8021BridgeBasePortTable_variables[] = {
    /*
     *
     * * magic number, variable type, ro/rw, callback fn, L, oidsuffix
     */

#define IEEE8021BRIDGEBASEPORTIFINDEX       1
    {
        IEEE8021BRIDGEBASEPORTIFINDEX, ASN_INTEGER, RWRITE,
        var_ieee8021BridgeBasePortTable, 2, {1, 3}
    },
#define IEEE8021BRIDGEBASEPORTDELAYEXCEEDEDDISCARDS     2
    {
        IEEE8021BRIDGEBASEPORTDELAYEXCEEDEDDISCARDS, ASN_COUNTER64, RONLY,
        var_ieee8021BridgeBasePortTable, 2, {1, 4}
    },
#define IEEE8021BRIDGEBASEPORTMTUEXCEEDEDDISCARDS       3
    {
        IEEE8021BRIDGEBASEPORTMTUEXCEEDEDDISCARDS, ASN_COUNTER64, RONLY,
        var_ieee8021BridgeBasePortTable, 2, {1, 5}
    },
#define IEEE8021BRIDGEBASEPORTCAPABILITIES      4
    {
        IEEE8021BRIDGEBASEPORTCAPABILITIES, ASN_OCTET_STR, RONLY,
        var_ieee8021BridgeBasePortTable, 2, {1, 6}
    },
#define IEEE8021BRIDGEBASEPORTTYPECAPABILITIES      5
    {
        IEEE8021BRIDGEBASEPORTTYPECAPABILITIES, ASN_OCTET_STR, RONLY,
        var_ieee8021BridgeBasePortTable, 2, {1, 7}
    },
#define IEEE8021BRIDGEBASEPORTTYPE      6
    {
        IEEE8021BRIDGEBASEPORTTYPE, ASN_INTEGER, RONLY,
        var_ieee8021BridgeBasePortTable, 2, {1, 8}
    },
#define IEEE8021BRIDGEBASEPORTEXTERNAL      7
    {
        IEEE8021BRIDGEBASEPORTEXTERNAL, ASN_INTEGER, RONLY,
        var_ieee8021BridgeBasePortTable, 2, {1, 9}
    },
#define IEEE8021BRIDGEBASEPORTADMINPOINTTOPOINT     8
    {
        IEEE8021BRIDGEBASEPORTADMINPOINTTOPOINT, ASN_INTEGER, RWRITE,
        var_ieee8021BridgeBasePortTable, 2, {1, 10}
    },
#define IEEE8021BRIDGEBASEPORTOPERPOINTTOPOINT      9
    {
        IEEE8021BRIDGEBASEPORTOPERPOINTTOPOINT, ASN_INTEGER, RONLY,
        var_ieee8021BridgeBasePortTable, 2, {1, 11}
    },
#define IEEE8021BRIDGEBASEPORTNAME      10
    {
        IEEE8021BRIDGEBASEPORTNAME, ASN_OCTET_STR, RONLY,
        var_ieee8021BridgeBasePortTable, 2, {1, 12}
    },
};


/*
 *
 * * Initializes the ieee8021BridgeBasePortTable module
 */
void
init_ieee8021BridgeBasePortTable(void)
{
    DEBUGMSGTL(("ieee8021BridgeBasePortTable", "Initializing\n"));

    /*
     * register ourselves with the agent to handle our mib tree
     */
    REGISTER_MIB("ieee8021BridgeBasePortTable",
                 ieee8021BridgeBasePortTable_variables, variable2,
                 ieee8021BridgeBasePortTable_variables_oid);

    /*
     * place any other initialization junk you need here
     */
}

static int get_next_ieee8021BridgeBasePortTableEntryKey(u_long *componentId, u_long *basePort)
{
    u_long tmp_componentId;
    dot1Port_info_t info;
    if ( *componentId > IEEE8021BRIDGECOMPONENT_CNT ) {
        return VTSS_RC_ERROR;
    }

    if ( *componentId  < IEEE8021BRIDGECOMPONENTID) {
        tmp_componentId = 1;
        info.dot1port = DOT1PORT_NO_NONE;
    } else {
        tmp_componentId = *componentId;
        info.dot1port = *basePort;
    }

    if (FALSE == dot1Port_get_next(&info)) {
        return VTSS_RC_ERROR;
    }
    *componentId = tmp_componentId;
    *basePort = info.dot1port;
    return VTSS_RC_OK;

}

static int get_ieee8021BridgeBasePortTableEntryKey(u_long *componentId, u_long *basePort)
{
    u_long tmp_componentId;
    u_long tmp_basePort;

    if ( *componentId > IEEE8021BRIDGECOMPONENT_CNT || *componentId < IEEE8021BRIDGECOMPONENTID ) {
        return VTSS_RC_ERROR;
    }

    if (*basePort == VTSS_VID_NULL) {
        return VTSS_RC_ERROR;
    }
    tmp_componentId = *componentId;
    tmp_basePort = *basePort - 1;


    if (VTSS_RC_OK != get_next_ieee8021BridgeBasePortTableEntryKey(&tmp_componentId, &tmp_basePort)) {
        return VTSS_RC_ERROR;
    }

    if (tmp_componentId != *componentId || tmp_basePort != *basePort) {
        return VTSS_RC_ERROR;
    }

    return VTSS_RC_OK;
}

static void update_ieee8021BridgeBasePortTable(vtss_isid_t isid, vtss_port_no_t port_idx, ieee8021BridgeBasePortTable_entry_t *table_entry_p)
{
    vtss_port_counters_t    counters;
    vlan_port_conf_t        port_conf;
    BOOL                    enable;
    mstp_port_param_t       conf;
    mstp_port_mgmt_status_t status, *ps = &status;

    if (FALSE == mstp_get_port_config(isid, port_idx, &enable, &conf)) {
        T_E("mstp_get_port_config: error(%d, %u)", isid, port_idx);
    }

    if (FALSE == mstp_get_port_status(0, L2PORT2PORT(isid, port_idx), ps)) {
        T_E("mstp_get_port_status: error(0, %u", L2PORT2PORT(isid, port_idx));
    }

    (void) port_mgmt_counters_get(isid, port_idx, &counters);
    (void) vlan_mgmt_port_conf_get(isid, port_idx, &port_conf, VLAN_USER_STATIC);

    table_entry_p->ieee8021BridgeBasePortDelayExceededDiscards.low = 0;
    table_entry_p->ieee8021BridgeBasePortMtuExceededDiscards.low   += counters.rmon.rx_etherStatsOversizePkts;
    table_entry_p->ieee8021BridgeBasePortCapabilities[0] = (char)0xe0;
    table_entry_p->ieee8021BridgeBasePortTypeCapabilities_len = 1;
    table_entry_p->ieee8021BridgeBasePortTypeCapabilities[0] = (char)0x82;
    table_entry_p->ieee8021BridgeBasePortTypeCapabilities_len = 1;
    table_entry_p->ieee8021BridgeBasePortType = VLAN_PORT_TYPE_UNAWARE == port_conf.port_type ? 8 : VLAN_PORT_TYPE_C == port_conf.port_type ? 2 : 1;
    table_entry_p->ieee8021BridgeBasePortExternal = 1;
    table_entry_p->ieee8021BridgeBasePortAdminPointToPoint = conf.adminPointToPointMAC == P2P_AUTO ? 3 : conf.adminPointToPointMAC == P2P_FORCETRUE ? 1 :
                                                             conf.adminPointToPointMAC == P2P_FORCEFALSE ? 2 : 0;
    table_entry_p->ieee8021BridgeBasePortOperPointToPoint = ps->core.operPointToPointMAC ? 1 : 2;

}




static int _get_ieee8021BridgeBasePortTableEntry(ieee8021BridgeBasePortTable_entry_t *table_entry)
{
    iftable_info_t      ifIndex_info;
    dot1Port_info_t     dot1Port_info;
    port_iter_t         pit;
    switch_iter_t       sit;
    aggr_mgmt_group_member_t aggr_members;

    dot1Port_info.dot1port = table_entry->ieee8021BridgeBasePort;

    (void) dot1Port_get(&dot1Port_info);

    ifIndex_info.isid = dot1Port_info.isid;
    ifIndex_info.if_id = dot1Port_info.if_id;

    switch (dot1Port_info.type) {
    case DOT1PORT_TYPE_PORT:
        ifIndex_info.type = IFTABLE_IFINDEX_TYPE_PORT;
        break;
    case DOT1PORT_TYPE_LLAG:
        ifIndex_info.type = IFTABLE_IFINDEX_TYPE_LLAG;
        break;
    case DOT1PORT_TYPE_GLAG:
        ifIndex_info.type = IFTABLE_IFINDEX_TYPE_GLAG;
        break;
    case DOT1PORT_TYPE_UNDEF:
    default:
        return VTSS_RC_ERROR;
    }

    (void) ifIndex_get_by_interface(&ifIndex_info);

    table_entry->ieee8021BridgeBasePortIfIndex = ifIndex_info.ifIndex;

    switch (dot1Port_info.type) {
    case DOT1PORT_TYPE_PORT:
        update_ieee8021BridgeBasePortTable(dot1Port_info.isid, dot1Port_info.if_id, table_entry);
#if VTSS_SWITCH_STACKABLE
        (void)snprintf(table_entry->ieee8021BridgeBasePortName, sizeof(table_entry->ieee8021BridgeBasePortName),
                       "Switch %2d - Port %2u", topo_isid2usid(dot1Port_info.isid), (u32)iport2uport(dot1Port_info.if_id));
#else
        (void)snprintf(table_entry->ieee8021BridgeBasePortName, sizeof(table_entry->ieee8021BridgeBasePortName),
                       "Port %2u", iport2uport(dot1Port_info.if_id));
#endif /* VTSS_SWITCH_STACKABLE */
        break;
    case DOT1PORT_TYPE_LLAG:
        if ((aggr_mgmt_port_members_get(dot1Port_info.isid, dot1Port_info.if_id, &aggr_members, FALSE) != VTSS_OK)
#ifdef VTSS_SW_OPTION_LACP
            && (aggr_mgmt_lacp_members_get(dot1Port_info.isid, dot1Port_info.if_id, &aggr_members, FALSE) != VTSS_OK)
#endif /* VTSS_SW_OPTION_LACP */
           ) {
            return FALSE;
        }

        (void)port_iter_init(&pit, NULL, dot1Port_info.isid, PORT_ITER_SORT_ORDER_IPORT, PORT_ITER_FLAGS_NORMAL);
        while (port_iter_getnext(&pit)) {
            if (!aggr_members.entry.member[pit.iport]) {
                continue;
            }
            update_ieee8021BridgeBasePortTable(dot1Port_info.isid, pit.iport, table_entry);
        }

#if VTSS_SWITCH_STACKABLE
        (void)snprintf(table_entry->ieee8021BridgeBasePortName, sizeof(table_entry->ieee8021BridgeBasePortName),
                       "Switch %2d - Local Link Aggregations %2lu", topo_isid2usid(dot1Port_info.isid), dot1Port_info.if_id);
#else
        (void)snprintf(table_entry->ieee8021BridgeBasePortName, sizeof(table_entry->ieee8021BridgeBasePortName),
                       "Link Aggregations %2lu", dot1Port_info.if_id);
#endif /* VTSS_SWITCH_STACKABLE */

        break;
    case DOT1PORT_TYPE_GLAG:
        (void)switch_iter_init(&sit, VTSS_ISID_GLOBAL, SWITCH_ITER_SORT_ORDER_ISID);
        while (switch_iter_getnext(&sit)) {
            if (aggr_mgmt_port_members_get(sit.isid, mgmt_aggr_id2no(dot1Port_info.if_id), &aggr_members, FALSE) != VTSS_OK) {
                continue;
            }

            (void)port_iter_init(&pit, NULL, sit.isid, PORT_ITER_SORT_ORDER_IPORT, PORT_ITER_FLAGS_NORMAL);
            while (port_iter_getnext(&pit)) {
                if (!aggr_members.entry.member[pit.iport]) {
                    continue;
                }
                update_ieee8021BridgeBasePortTable(sit.isid, pit.iport, table_entry);
            }
        }
        (void)snprintf(table_entry->ieee8021BridgeBasePortName, sizeof(table_entry->ieee8021BridgeBasePortName),
                       "Global Link Aggregations %lu", dot1Port_info.if_id);
        break;
    case DOT1PORT_TYPE_UNDEF:
    default:
        return VTSS_RC_ERROR;
    }
    return VTSS_RC_OK;

}


static int
getfirst_ieee8021BridgeBasePortTableEntry
(ieee8021BridgeBasePortTable_entry_t *table_entry)
{
    u_long tmp_componentId = 0;
    u_long tmp_basePort = 0;

    if (VTSS_RC_OK != get_next_ieee8021BridgeBasePortTableEntryKey(&tmp_componentId, &tmp_basePort)) {
        return VTSS_RC_ERROR;
    }
    table_entry->ieee8021BridgeBasePortComponentId = tmp_componentId;
    table_entry->ieee8021BridgeBasePort = tmp_basePort;

    return _get_ieee8021BridgeBasePortTableEntry(table_entry);
}

static int
get_ieee8021BridgeBasePortTableEntry(ieee8021BridgeBasePortTable_entry_t *
                                     table_entry, BOOL getnext)
{
    u_long tmp_componentId = table_entry->ieee8021BridgeBasePortComponentId;
    u_long tmp_basePort = table_entry->ieee8021BridgeBasePort;

    if (getnext) {
        if (VTSS_RC_OK != get_next_ieee8021BridgeBasePortTableEntryKey(&tmp_componentId, &tmp_basePort)) {
            return VTSS_RC_ERROR;
        }
    } else {
        if (VTSS_RC_OK != get_ieee8021BridgeBasePortTableEntryKey(&tmp_componentId, &tmp_basePort)) {
            T_E("VTSS_RC_ERROR");
            return VTSS_RC_ERROR;
        }
    }

    table_entry->ieee8021BridgeBasePortComponentId = tmp_componentId;
    table_entry->ieee8021BridgeBasePort = tmp_basePort;

    return _get_ieee8021BridgeBasePortTableEntry(table_entry);
}
static int
set_ieee8021BridgeBasePortTableEntry(ieee8021BridgeBasePortTable_entry_t *
                                     table_entry)
{
    dot1Port_info_t     info;
    mstp_port_param_t   conf;
    BOOL                enable;
    port_iter_t         pit;
    switch_iter_t       sit;
    aggr_mgmt_group_member_t aggr_members;


    info.dot1port = table_entry->ieee8021BridgeBasePort;
    (void) dot1Port_get(&info);

    switch (info.type) {
    case DOT1PORT_TYPE_PORT:
        if (FALSE == mstp_get_port_config(info.isid, info.if_id, &enable, &conf)) {
            T_E("mstp_get_port_config: error(%d, %lu)", info.isid, info.if_id);
            return VTSS_RC_ERROR;
        }

        conf.adminPointToPointMAC =  table_entry->ieee8021BridgeBasePortAdminPointToPoint == 3 ? P2P_AUTO : table_entry->ieee8021BridgeBasePortAdminPointToPoint == 2 ? P2P_FORCEFALSE :
                                     table_entry->ieee8021BridgeBasePortAdminPointToPoint == 1 ? P2P_FORCETRUE : 0;

        if (FALSE == mstp_set_port_config(info.isid, info.if_id, enable, &conf)) {
            T_E("mstp_get_port_config: error(%d, %lu)", info.isid, info.if_id);
            return VTSS_RC_ERROR;
        }
        break;
    case DOT1PORT_TYPE_LLAG:
        if ((aggr_mgmt_port_members_get(info.isid, info.if_id, &aggr_members, FALSE) != VTSS_OK)
#ifdef VTSS_SW_OPTION_LACP
            && (aggr_mgmt_lacp_members_get(info.isid, info.if_id, &aggr_members, FALSE) != VTSS_OK)
#endif /* VTSS_SW_OPTION_LACP */
           ) {
            return FALSE;
        }

        (void)port_iter_init(&pit, NULL, info.isid, PORT_ITER_SORT_ORDER_IPORT, PORT_ITER_FLAGS_NORMAL);
        while (port_iter_getnext(&pit)) {
            if (!aggr_members.entry.member[pit.iport]) {
                continue;
            }
            if (FALSE == mstp_get_port_config(info.isid, pit.iport, &enable, &conf)) {
                T_E("mstp_get_port_config: error(%d, %u)", info.isid, pit.iport);
                return VTSS_RC_ERROR;
            }

            conf.adminPointToPointMAC =  table_entry->ieee8021BridgeBasePortAdminPointToPoint == 3 ? P2P_AUTO : table_entry->ieee8021BridgeBasePortAdminPointToPoint == 2 ? P2P_FORCEFALSE :
                                         table_entry->ieee8021BridgeBasePortAdminPointToPoint == 1 ? P2P_FORCETRUE : 0;

            if (FALSE == mstp_set_port_config(info.isid, pit.iport, enable, &conf)) {
                T_E("mstp_get_port_config: error(%d, %u)", info.isid, pit.iport);
                return VTSS_RC_ERROR;
            }

        }
        break;
    case DOT1PORT_TYPE_GLAG:
        (void)switch_iter_init(&sit, VTSS_ISID_GLOBAL, SWITCH_ITER_SORT_ORDER_ISID);
        while (switch_iter_getnext(&sit)) {
            if (aggr_mgmt_port_members_get(sit.isid, mgmt_aggr_id2no(info.if_id), &aggr_members, FALSE) != VTSS_OK) {
                continue;
            }

            (void)port_iter_init(&pit, NULL, sit.isid, PORT_ITER_SORT_ORDER_IPORT, PORT_ITER_FLAGS_NORMAL);
            while (port_iter_getnext(&pit)) {
                if (!aggr_members.entry.member[pit.iport]) {
                    continue;
                }
                if (FALSE == mstp_get_port_config(sit.isid, pit.iport, &enable, &conf)) {
                    T_E("mstp_get_port_config: error(%d, %u)", sit.isid, pit.iport);
                    return VTSS_RC_ERROR;
                }

                conf.adminPointToPointMAC =  table_entry->ieee8021BridgeBasePortAdminPointToPoint == 3 ? P2P_AUTO : table_entry->ieee8021BridgeBasePortAdminPointToPoint == 2 ? P2P_FORCEFALSE :
                                             table_entry->ieee8021BridgeBasePortAdminPointToPoint == 1 ? P2P_FORCETRUE : 0;

                if (FALSE == mstp_set_port_config(sit.isid, pit.iport, enable, &conf)) {
                    T_E("mstp_get_port_config: error(%d, %u)", sit.isid, pit.iport);
                    return VTSS_RC_ERROR;
                }
            }
        }
        break;
    case DOT1PORT_TYPE_UNDEF:
    default:
        return VTSS_RC_ERROR;

    }
    return VTSS_RC_OK;

}

static int
parse_ieee8021BridgeBasePortTable(oid *name, size_t *length, int exact,
                                  ieee8021BridgeBasePortTable_entry_t *
                                  table_entry)
{
    size_t         op_pos = 11 + 2;
    oid *op = (oid *) (name + op_pos);
    if (exact && *length < (11 + 1 + 2)) {
        return -1;
    } else if (!exact && *length <= op_pos) {
        if (getfirst_ieee8021BridgeBasePortTableEntry(table_entry)) {
            return -1;
        }
        return 1;              /* getfirst */
    }
    memset(table_entry, 0, sizeof(*table_entry));
    if (*length > op_pos) {
        table_entry->ieee8021BridgeBasePortComponentId = (u_long) * op++;
        op_pos++;
    } else if (exact) {
        return -1;
    } else {
        return 0;
    }
    if (*length > op_pos) {
        table_entry->ieee8021BridgeBasePort = (u_long) * op++;
        op_pos++;
    } else if (exact) {
        return -1;
    } else {
        return 0;
    }
    if (exact && *length != op_pos) {
        return -1;
    }
    return 0;
}
static int
fillobj_ieee8021BridgeBasePortTable(oid *name, size_t *length,
                                    ieee8021BridgeBasePortTable_entry_t *
                                    table_entry)
{
    int            name_pos = 11 + 2;
    name[name_pos++] =
        (oid) table_entry->ieee8021BridgeBasePortComponentId;
    name[name_pos++] = (oid) table_entry->ieee8021BridgeBasePort;
    *length = name_pos;
    return 0;
}


/*
 *
 * * var_ieee8021BridgeBasePortTable():
 * *   Handle this table separately from the scalar value case.
 * *   The workings of this are basically the same as for var_ieee8021BridgeBasePortTable above.
 */
u_char *var_ieee8021BridgeBasePortTable(struct variable *vp,
                                        oid *name, size_t *length,
                                        int exact, size_t *var_len,
                                        WriteMethod **
                                        write_method)
{
    int            rc;
    oid newname[MAX_OID_LEN];
    size_t         newname_len;
    ieee8021BridgeBasePortTable_entry_t table_entry;
    *write_method = NULL;
    memcpy((char *) newname, (char *) vp->name,
           (int) (vp->namelen * sizeof(oid)));
    newname_len = vp->namelen;
    if (memcmp(name, vp->name, sizeof(oid) * vp->namelen) != 0) {
        memcpy(name, vp->name, sizeof(oid) * vp->namelen);
        *length = vp->namelen;
    }
    if ((rc =
             parse_ieee8021BridgeBasePortTable(name, length, exact,
                                               &table_entry)) < 0) {
        return NULL;
    } else if (rc > 0) {       /* getfirst */
        if (fillobj_ieee8021BridgeBasePortTable
            (newname, &newname_len, &table_entry)) {
            return NULL;
        }
    } else {

        do {
            if (get_ieee8021BridgeBasePortTableEntry
                (&table_entry, exact ? FALSE : TRUE)) {
                return NULL;
            }
            if (fillobj_ieee8021BridgeBasePortTable
                (newname, &newname_len, &table_entry)) {
                return NULL;
            }
            if (exact) {
                break;
            }
            rc = snmp_oid_compare(newname, newname_len, name, *length);
        } while (rc < 0);
    }

    /*
     *
     * * fill in object part of name for current entry
     */
    memcpy((char *) name, (char *) newname,
           (int) (newname_len * sizeof(oid)));
    *length = newname_len;

    /*
     *
     * * this is where we do the value assignments for the mib results.
     */
    switch (vp->magic) {
    case IEEE8021BRIDGEBASEPORTIFINDEX: {
        *write_method = write_ieee8021BridgeBasePortIfIndex;
        ieee8021BridgeMib_global_ret.long_ret =
            table_entry.ieee8021BridgeBasePortIfIndex;
        *var_len = sizeof(ieee8021BridgeMib_global_ret.long_ret);
        return (u_char *) & ieee8021BridgeMib_global_ret.long_ret;
    }
    case IEEE8021BRIDGEBASEPORTDELAYEXCEEDEDDISCARDS: {
        ieee8021BridgeMib_global_ret.c64_ret =
            table_entry.ieee8021BridgeBasePortDelayExceededDiscards;
        *var_len = sizeof(ieee8021BridgeMib_global_ret.c64_ret);
        return (u_char *) & ieee8021BridgeMib_global_ret.c64_ret;
    }
    case IEEE8021BRIDGEBASEPORTMTUEXCEEDEDDISCARDS: {
        ieee8021BridgeMib_global_ret.c64_ret =
            table_entry.ieee8021BridgeBasePortMtuExceededDiscards;
        *var_len = sizeof(ieee8021BridgeMib_global_ret.c64_ret);
        return (u_char *) & ieee8021BridgeMib_global_ret.c64_ret;
    }
    case IEEE8021BRIDGEBASEPORTCAPABILITIES: {
        strcpy(ieee8021BridgeMib_global_ret.string_ret,
               table_entry.ieee8021BridgeBasePortCapabilities);
        *var_len = strlen(ieee8021BridgeMib_global_ret.string_ret);
        return (u_char *) ieee8021BridgeMib_global_ret.string_ret;
    }
    case IEEE8021BRIDGEBASEPORTTYPECAPABILITIES: {
        strcpy(ieee8021BridgeMib_global_ret.string_ret,
               table_entry.ieee8021BridgeBasePortTypeCapabilities);
        *var_len = strlen(ieee8021BridgeMib_global_ret.string_ret);
        return (u_char *) ieee8021BridgeMib_global_ret.string_ret;
    }
    case IEEE8021BRIDGEBASEPORTTYPE: {
        ieee8021BridgeMib_global_ret.long_ret = table_entry.ieee8021BridgeBasePortType;
        *var_len = sizeof(ieee8021BridgeMib_global_ret.long_ret);
        return (u_char *) & ieee8021BridgeMib_global_ret.long_ret;
    }
    case IEEE8021BRIDGEBASEPORTEXTERNAL: {
        ieee8021BridgeMib_global_ret.long_ret =
            table_entry.ieee8021BridgeBasePortExternal;
        *var_len = sizeof(ieee8021BridgeMib_global_ret.long_ret);
        return (u_char *) & ieee8021BridgeMib_global_ret.long_ret;
    }
    case IEEE8021BRIDGEBASEPORTADMINPOINTTOPOINT: {
        *write_method = write_ieee8021BridgeBasePortAdminPointToPoint;
        ieee8021BridgeMib_global_ret.long_ret =
            table_entry.ieee8021BridgeBasePortAdminPointToPoint;
        *var_len = sizeof(ieee8021BridgeMib_global_ret.long_ret);
        return (u_char *) & ieee8021BridgeMib_global_ret.long_ret;
    }
    case IEEE8021BRIDGEBASEPORTOPERPOINTTOPOINT: {
        ieee8021BridgeMib_global_ret.long_ret =
            table_entry.ieee8021BridgeBasePortOperPointToPoint;
        *var_len = sizeof(ieee8021BridgeMib_global_ret.long_ret);
        return (u_char *) & ieee8021BridgeMib_global_ret.long_ret;
    }
    case IEEE8021BRIDGEBASEPORTNAME: {
        strcpy(ieee8021BridgeMib_global_ret.string_ret,
               table_entry.ieee8021BridgeBasePortName);
        *var_len = strlen(ieee8021BridgeMib_global_ret.string_ret);
        return (u_char *) ieee8021BridgeMib_global_ret.string_ret;
    }
    default:
        DEBUGMSGTL(("snmpd",
                    "unknown sub-id %d in var_ieee8021BridgeBasePortTable\n",
                    vp->magic));
    }
    return NULL;
}
int
write_ieee8021BridgeBasePortIfIndex(int action, u_char *var_val,
                                    u_char var_val_type,
                                    size_t var_val_len, u_char *statP,
                                    oid *name, size_t name_len)
{
    long           set_value = var_val ? *((long *) var_val) : 0;
    ieee8021BridgeBasePortTable_entry_t table_entry;
    switch (action) {
    case RESERVE1: {
        if (var_val_type != ASN_INTEGER) {
            (void) snmp_log(LOG_ERR,
                            "write to ieee8021BridgeBasePortIfIndex: not ASN_INTEGER\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(long)) {
            (void) snmp_log(LOG_ERR,
                            "write to ieee8021BridgeBasePortIfIndex: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        break;
    }
    case RESERVE2: {

        /*
         *
         * * Allocate memory and similar resources
         */
        break;
    }
    case FREE: {

        /*
         *
         * *Release any resources that have been allocated
         */
        break;
    }
    case ACTION: {

        /*
         *
         * * The variable has been stored in 'value' for you to use,
         * * and you have just been asked to do something with it.
         * * Note that anything done here must be reversable in the UNDO case
         */
        /*
         *
         * * Save to current configuration
         */
        /*
         *
         * * We don't implement UNDO in EstaX project
         */
        break;
    }
    case UNDO: {

        /*
         *
         * * Back out any changes made in the ACTION case
         */
        /*
         *
         * * Restore current configuration from old configuration
         */
        /*
         *
         * * We don't implement UNDO in EstaX project
         */
        break;
    }
    case COMMIT: {

        /*
         *
         * * Things are working well, so it's now safe to make the change
         * * permanently.  Make sure that anything done here can't fail!
         */
        /*
         *
         * * Update old configuration
         */
        /*
         *
         * * In EstaX project, we set new configuration directly
         */
        if (parse_ieee8021BridgeBasePortTable
            (name, &name_len, TRUE, &table_entry)) {
            return SNMP_ERR_COMMITFAILED;
        }
        if (get_ieee8021BridgeBasePortTableEntry(&table_entry, FALSE)) {
            return SNMP_ERR_COMMITFAILED;
        }
        table_entry.ieee8021BridgeBasePortIfIndex = set_value;
        if (set_ieee8021BridgeBasePortTableEntry(&table_entry)) {
            return SNMP_ERR_COMMITFAILED;
        }
        break;
    }
    }
    return SNMP_ERR_NOERROR;
}
int
write_ieee8021BridgeBasePortAdminPointToPoint(int action,
                                              u_char *var_val,
                                              u_char var_val_type,
                                              size_t var_val_len,
                                              u_char *statP, oid *name,
                                              size_t name_len)
{
    long           set_value = var_val ? *((long *) var_val) : 0;
    ieee8021BridgeBasePortTable_entry_t table_entry;
    switch (action) {
    case RESERVE1: {
        if (var_val_type != ASN_INTEGER) {
            (void) snmp_log(LOG_ERR,
                            "write to ieee8021BridgeBasePortAdminPointToPoint: not ASN_INTEGER\n");
            return SNMP_ERR_WRONGTYPE;
        }
        if (var_val_len > sizeof(long)) {
            (void) snmp_log(LOG_ERR,
                            "write to ieee8021BridgeBasePortAdminPointToPoint: bad length\n");
            return SNMP_ERR_WRONGLENGTH;
        }
        if (set_value != 1  && set_value != 2  && set_value != 3 ) {
            (void) snmp_log(LOG_ERR,
                            "write to ieee8021BridgeBasePortAdminPointToPoint: bad value\n");
            return SNMP_ERR_WRONGVALUE;
        }
        break;
    }
    case RESERVE2: {

        /*
         *
         * * Allocate memory and similar resources
         */
        break;
    }
    case FREE: {

        /*
         *
         * *Release any resources that have been allocated
         */
        break;
    }
    case ACTION: {

        /*
         *
         * * The variable has been stored in 'value' for you to use,
         * * and you have just been asked to do something with it.
         * * Note that anything done here must be reversable in the UNDO case
         */
        /*
         *
         * * Save to current configuration
         */
        /*
         *
         * * We don't implement UNDO in EstaX project
         */
        break;
    }
    case UNDO: {

        /*
         *
         * * Back out any changes made in the ACTION case
         */
        /*
         *
         * * Restore current configuration from old configuration
         */
        /*
         *
         * * We don't implement UNDO in EstaX project
         */
        break;
    }
    case COMMIT: {

        /*
         *
         * * Things are working well, so it's now safe to make the change
         * * permanently.  Make sure that anything done here can't fail!
         */
        /*
         *
         * * Update old configuration
         */
        /*
         *
         * * In EstaX project, we set new configuration directly
         */
        if (parse_ieee8021BridgeBasePortTable
            (name, &name_len, TRUE, &table_entry)) {
            return SNMP_ERR_COMMITFAILED;
        }
        if (get_ieee8021BridgeBasePortTableEntry(&table_entry, FALSE)) {
            return SNMP_ERR_COMMITFAILED;
        }
        table_entry.ieee8021BridgeBasePortAdminPointToPoint =
            set_value;
        if (set_ieee8021BridgeBasePortTableEntry(&table_entry)) {
            return SNMP_ERR_COMMITFAILED;
        }
        break;
    }
    }
    return SNMP_ERR_NOERROR;
}

/*
 * Initializes the dot1dBridge module
 */
void
init_ieee8021BridgeMib(void)
{
    init_ieee8021BridgeBasePortTable();
}

