/*
 *
 * * Note: this file originally auto-generated by mib2c using
 * *        : mib2c.old-api.conf,v 1.5 2010/07/19 09:20:45 annapurna Exp $
 */
#ifndef IEEE8021BRIDGEMIB_H
#define IEEE8021BRIDGEMIB_H

/*
 * function declarations
 */
void            init_ieee8021BridgeMib(void);
FindVarMethod var_ieee8021BridgeBasePortTable;
WriteMethod write_ieee8021BridgeBasePortIfIndex;
WriteMethod write_ieee8021BridgeBasePortAdminPointToPoint;

#endif  /* IEEE8021BRIDGEMIB_H */

