/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef IEEE8021QBRIDGEMIB_H
#define IEEE8021QBRIDGEMIB_H

#define IEEE8021_Q_BRIDGE
/*
 * function declarations
 */
void            init_ieee8021QBridgeMib(void);
FindVarMethod   var_ieee8021QBridgeMib;
FindVarMethod   var_ieee8021QBridgeTable;
FindVarMethod   var_ieee8021QBridgeCVlanPortTable;
FindVarMethod   var_ieee8021QBridgeFdbTable;
FindVarMethod   var_ieee8021QBridgeTpFdbTable;
FindVarMethod   var_ieee8021QBridgeTpGroupTable;
FindVarMethod   var_ieee8021QBridgeForwardAllTable;
FindVarMethod   var_ieee8021QBridgeForwardUnregisteredTable;
FindVarMethod   var_ieee8021QBridgeStaticUnicastTable;
FindVarMethod   var_ieee8021QBridgeStaticMulticastTable;
FindVarMethod   var_ieee8021QBridgeVlanCurrentTable;
FindVarMethod   var_ieee8021QBridgeVlanStaticTable;
FindVarMethod   var_ieee8021QBridgeNextFreeLocalVlanTable;
FindVarMethod   var_ieee8021QBridgePortVlanTable;
FindVarMethod   var_ieee8021QBridgePortVlanStatisticsTable;
FindVarMethod   var_ieee8021QBridgeLearningConstraintsTable;
FindVarMethod   var_ieee8021QBridgeLearningConstraintDefaultsTable;
FindVarMethod   var_ieee8021QBridgeProtocolGroupTable;
FindVarMethod   var_ieee8021QBridgeProtocolPortTable;
WriteMethod     write_ieee8021QBridgeMvrpEnabledStatus;
WriteMethod     write_ieee8021QBridgeCVlanPortRowStatus;
WriteMethod     write_ieee8021QBridgeFdbAgingTime;
WriteMethod     write_ieee8021QBridgeForwardAllStaticPorts;
WriteMethod     write_ieee8021QBridgeForwardAllForbiddenPorts;
WriteMethod     write_ieee8021QBridgeForwardUnregisteredStaticPorts;
WriteMethod     write_ieee8021QBridgeForwardUnregisteredForbiddenPorts;
WriteMethod     write_ieee8021QBridgeStaticUnicastStaticEgressPorts;
WriteMethod     write_ieee8021QBridgeStaticUnicastForbiddenEgressPorts;
WriteMethod     write_ieee8021QBridgeStaticUnicastStorageType;
WriteMethod     write_ieee8021QBridgeStaticUnicastRowStatus;
WriteMethod     write_ieee8021QBridgeStaticMulticastStaticEgressPorts;
WriteMethod     write_ieee8021QBridgeStaticMulticastForbiddenEgressPorts;
WriteMethod     write_ieee8021QBridgeStaticMulticastStorageType;
WriteMethod     write_ieee8021QBridgeStaticMulticastRowStatus;
WriteMethod     write_ieee8021QBridgeVlanStaticName;
WriteMethod     write_ieee8021QBridgeVlanStaticEgressPorts;
WriteMethod     write_ieee8021QBridgeVlanForbiddenEgressPorts;
WriteMethod     write_ieee8021QBridgeVlanStaticUntaggedPorts;
WriteMethod     write_ieee8021QBridgeVlanStaticRowStatus;
WriteMethod     write_ieee8021QBridgePvid;
WriteMethod     write_ieee8021QBridgePortAcceptableFrameTypes;
WriteMethod     write_ieee8021QBridgePortIngressFiltering;
WriteMethod     write_ieee8021QBridgePortMvrpEnabledStatus;
WriteMethod     write_ieee8021QBridgePortRestrictedVlanRegistration;
WriteMethod     write_ieee8021QBridgeLearningConstraintsType;
WriteMethod     write_ieee8021QBridgeLearningConstraintsStatus;
WriteMethod     write_ieee8021QBridgeLearningConstraintDefaultsSet;
WriteMethod     write_ieee8021QBridgeLearningConstraintDefaultsType;
WriteMethod     write_ieee8021QBridgeProtocolGroupId;
WriteMethod     write_ieee8021QBridgeProtocolGroupRowStatus;
WriteMethod     write_ieee8021QBridgeProtocolPortGroupVid;
WriteMethod     write_ieee8021QBridgeProtocolPortRowStatus;

#endif                          /* IEEE8021QBRIDGEMIB_H */

