/*

 Vitesse Switch Software.

 Copyright (c) 2002-2011 Vitesse Semiconductor Corporation "Vitesse". All
 Rights Reserved.

 Unpublished rights reserved under the copyright laws of the United States of
 America, other countries and international treaties. Permission to use, copy,
 store and modify, the software and its source code is granted. Permission to
 integrate into other products, disclose, transmit and distribute the software
 in an absolute machine readable format (e.g. HEX file) is also granted.  The
 source code of the software may not be disclosed, transmitted or distributed
 without the written permission of Vitesse. The software and its source code
 may only be used in products utilizing the Vitesse switch products.

 This copyright notice must appear in any copy, modification, disclosure,
 transmission or distribution of the software. Vitesse retains all ownership,
 copyright, trade secret and proprietary rights in the software.

 THIS SOFTWARE HAS BEEN PROVIDED "AS IS," WITHOUT EXPRESS OR IMPLIED WARRANTY
 INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 FOR A PARTICULAR USE AND NON-INFRINGEMENT.

*/
/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf
 */

#ifndef IEEE8021MSTPMIB_H
#define IEEE8021MSTPMIB_H
#define    IEEE8021MSTPMIB_OBJECTS 1
#define    SNMP_OID_NAME_INDEX     2

#define IEEE_8021_SUPPORTED_MSTP 1
/* function declarations */
void send_mstp_trap(u32 event_mask);
void snmp_new_root_notification(void);
void snmp_topology_change_notification(void);

#define SNMP_BRIDGEID_LEN   8
#define MSTID_CIST          0   /* CIST is MSTI0 - MSTID zero */

#define   SNMP_MSTP_FALSE              2
#define   SNMP_MSTP_TRUE               1

#define   SNMP_MSTP_VID_MAX            128
#define   SNMP_MSTP_CFG_DIGEST_MAX     16
#define   SNMP_SET_MASK_MAX            256
#define   SNMP_SET_MASK_VAL            8
#define   SNMP_MSTP_ROOT_PORT          1
#define   SNMP_MSTP_ALTERNATE_PORT     2
#define   SNMP_MSTP_DESIGNATE_PORT     3
#define   SNMP_MSTP_BACKUP_PORT        4
#define   SNMP_MSTP_PORT_ERROR         5
#define   SNMP_CONFIG_NAME_BUF_LEN     50
#define   SNMP_CONFIG_NAME_MAXLEN      32
#define   NEWROOTTRAPINST              1
#define   TOPOLOGYCHANGETRAPINST       2
#define SNMP_DEBUG_LOG_ERROR  { \
                                 if (log_rc < 0) {\
 T_D("%s:SNMP log return code error, log error:%d ", __FUNCTION__, log_rc);\
                              } \
                          }
typedef struct {
    u32        ieee8021MstpCistComponentId;
    u8         ieee8021MstpCistBridgeIdentifier[SNMP_BRIDGEID_LEN];
    bool       ieee8021MstpCistTopologyChange;
    u8         ieee8021MstpCistRegionalRootIdentifier[SNMP_BRIDGEID_LEN];
    u32        ieee8021MstpCistPathCost;
    u32        ieee8021MstpCistMaxHops;
} ieee8021MstpCistTable_entry_t;

typedef struct {
    u32              ieee8021MstpComponentId;
    u32              ieee8021MstpId;
    u8               ieee8021MstpBridgeId[SNMP_BRIDGEID_LEN];
    u32              ieee8021MstpTimeSinceTopologyChange;
    struct counter64 ieee8021MstpTopologyChanges;
    bool             ieee8021MstpTopologyChange;
    u8               ieee8021MstpDesignatedRoot[SNMP_BRIDGEID_LEN];
    u32              ieee8021MstpRootPathCost;
    u32              ieee8021MstpRootPort;
    u32              ieee8021MstpBridgePriority;
    u8               ieee8021MstpVids0[SNMP_MSTP_VID_MAX];
    u8               ieee8021MstpVids1[SNMP_MSTP_VID_MAX];
    u8               ieee8021MstpVids2[SNMP_MSTP_VID_MAX];
    u8               ieee8021MstpVids3[SNMP_MSTP_VID_MAX];
    u32              ieee8021MstpRowStatus;
} ieee8021MstpTable_entry_t;

typedef struct {
    u32        ieee8021MstpCistPortComponentId;
    u32        ieee8021MstpCistPortNum;
    u32        ieee8021MstpCistPortUptime;
    u8         ieee8021MstpCistPortDesignatedRoot[SNMP_BRIDGEID_LEN];
    bool       ieee8021MstpCistPortTopologyChangeAck;
    u32        ieee8021MstpCistPortHelloTime;
    bool       ieee8021MstpCistPortOperEdgePort;
    bool       ieee8021MstpCistPortMacEnabled;
    bool       ieee8021MstpCistPortMacOperational;
    bool       ieee8021MstpCistPortRestrictedRole;
    bool       ieee8021MstpCistPortRestrictedTcn;
    u32        ieee8021MstpCistPortRole;
    bool       ieee8021MstpCistPortDisputed;
    u8         ieee8021MstpCistPortCistRegionalRootId[SNMP_BRIDGEID_LEN];
    u32        ieee8021MstpCistPortCistPathCost;
    bool       ieee8021MstpCistPortProtocolMigration;
    bool       ieee8021MstpCistPortEnableBPDURx;
    bool       ieee8021MstpCistPortEnableBPDUTx;
    u8         ieee8021MstpCistPortPseudoRootId[SNMP_BRIDGEID_LEN];
    bool       ieee8021MstpCistPortIsL2Gp;
} ieee8021MstpCistPortTable_entry_t;

typedef struct {
    u32        ieee8021MstpPortComponentId;
    u32        ieee8021MstpPortMstId;
    u32        ieee8021MstpPortNum;
    u32        ieee8021MstpPortUptime;
    u32        ieee8021MstpPortState;
    u32        ieee8021MstpPortPriority;
    u32        ieee8021MstpPortPathCost;
    u8         ieee8021MstpPortDesignatedRoot[SNMP_BRIDGEID_LEN];
    u32        ieee8021MstpPortDesignatedCost;
    u8         ieee8021MstpPortDesignatedBridge[SNMP_BRIDGEID_LEN];
    u32        ieee8021MstpPortDesignatedPort;
    u32        ieee8021MstpPortRole;
    bool       ieee8021MstpPortDisputed;
} ieee8021MstpPortTable_entry_t;

typedef struct {
    u32        ieee8021MstpFidToMstiComponentId;
    u32        ieee8021MstpFidToMstiFid;
    u32        ieee8021MstpFidToMstiMstId;
} ieee8021MstpFidToMstiTable_entry_t;

typedef struct {
    u32        ieee8021MstpVlanComponentId;
    u32        ieee8021MstpVlanId;
    u32        ieee8021MstpVlanMstId;
} ieee8021MstpVlanTable_entry_t;

typedef struct {
    u32        ieee8021MstpConfigIdComponentId;
    u32        ieee8021MstpConfigIdFormatSelector;
    u8         ieee8021MstpConfigurationName[SNMP_CONFIG_NAME_MAXLEN];
    u32        ieee8021MstpRevisionLevel;
    u8         ieee8021MstpConfigurationDigest[SNMP_MSTP_CFG_DIGEST_MAX];
} ieee8021MstpConfigIdTable_entry_t;


void
init_ieee8021MstpMib (void);

FindVarMethod var_ieee8021MstpMib;
FindVarMethod var_ieee8021MstpCistTable;
FindVarMethod var_ieee8021MstpTable;
FindVarMethod var_ieee8021MstpCistPortTable;
FindVarMethod var_ieee8021MstpPortTable;
FindVarMethod var_ieee8021MstpFidToMstiTable;
FindVarMethod var_ieee8021MstpVlanTable;
FindVarMethod var_ieee8021MstpConfigIdTable;
WriteMethod write_ieee8021MstpCistMaxHops;
WriteMethod write_ieee8021MstpBridgePriority;
WriteMethod write_ieee8021MstpRowStatus;
WriteMethod write_ieee8021MstpCistPortAdminPathCost;
WriteMethod write_ieee8021MstpCistPortAdminEdgePort;
WriteMethod write_ieee8021MstpCistPortMacEnabled;
WriteMethod write_ieee8021MstpCistPortRestrictedRole;
WriteMethod write_ieee8021MstpCistPortRestrictedTcn;
WriteMethod write_ieee8021MstpCistPortProtocolMigration;
WriteMethod write_ieee8021MstpCistPortEnableBPDURx;
WriteMethod write_ieee8021MstpCistPortEnableBPDUTx;
WriteMethod write_ieee8021MstpCistPortPseudoRootId;
WriteMethod write_ieee8021MstpCistPortIsL2Gp;
WriteMethod write_ieee8021MstpPortPriority;
WriteMethod write_ieee8021MstpPortPathCost;
WriteMethod write_ieee8021MstpFidToMstiMstId;
WriteMethod write_ieee8021MstpConfigIdFormatSelector;
WriteMethod write_ieee8021MstpConfigurationName;
WriteMethod write_ieee8021MstpRevisionLevel;

#endif /* IEEE8021MSTPMIB_H */

