/*
 * registers.h
 *
 *  Created on: Mar 6, 2013
 *      Author: eric
 */

#ifndef REGISTERS_H_
#define REGISTERS_H_

#include "vns_types.h"

#define FPGA_I2C_ADDR 	0x3C /* i2c address of the FPGA */

typedef enum{
    FPGA_IRIG_IN_CHANNEL_ID = 0,		//0
    FPGA_IRIG_IN_SRC,
    FPGA_IRIG_IN_ENABLE,
    FPGA_IRIG_IN_SIGNAL,
    FPGA_UPDATE_CHUNK_MODE_ENABLE, /* Not useful right now; have to write entire packet to register & no way to know if failure occurred*/
    FPGA_UPDATE_LOAD_FACTORY_IMG,
    FPGA_UPDATE_FACTORY_IMG,
    FPGA_IRIG_IN_TIME_MSEC,
    FPGA_IRIG_IN_TIME_SEC,
    FPGA_IRIG_IN_TIME_MIN,
    FPGA_IRIG_IN_TIME_HOUR,			/* 10 */
    FPGA_IRIG_IN_TIME_DAY,
    FPGA_IRIG_IN_TIME_TDAY,
    FPGA_IRIG_IN_TIME_YEAR,
    FPGA_IRIG_IN_HEALTH,
    FPGA_UPDATE_STATUS,
    FPGA_UPDATE_FACTORY,
    FPGA_UPDATE_DONE,
    FPGA_UPDATE_ERASE_DONE,
    FPGA_IRIG_IN_RTC_CAL_LSB,
    FPGA_IRIG_IN_RTC_DIFF_LSW,	/* 20 */
    FPGA_IRIG_IN_CAL_MSB,
    FPGA_IRIG_IN_CAL_LSB,
    FPGA_1588_IN_CAL_MSB,
    FPGA_1588_IN_CAL_LSB,
    FPGA_IRIG_IN_OFFSET_MULTIPLIER,
    FPGA_IRIG_IN_GPS_SECOND_WRITE,
    FPGA_IRIG_IN_GPS_SECOND_READ,
    FPGA_IRIG_IN_RTC_VAL_LSW,
    FPGA_IRIG_IN_RTC_VAL_MSW,
    FPGA_IRIG_IN_INTERRUPT,
    FPGA_FIRMWARE_VERSION_MINOR,
    FPGA_FIRMWARE_VERSION_MAJOR,		/* 30 */
    FPGA_IRIG_OUT_CHANNEL_ID,
    FPGA_IRIG_OUT_TIMECODE,
    FPGA_IRIG_OUT_ENABLE,
    FPGA_IEEE_1588_MODE,
    FPGA_IRIG_OUT_MODE,
    FPGA_TTL_1PPS_ENABLE,
    FPGA_UPDATE_DATA,
    FPGA_IRIG_OUT_HEALTH,
    FPGA_IRIG_OUT_RTC_LSW,
    FPGA_IRIG_OUT_RTC_MSW,	/* 40 */
    FPGA_IRIG_OUT_PHASE_MULT0,
    FPGA_IRIG_OUT_PHASE_MULT1,
    FPGA_IRIG_OUT_TCG_CAL_COARSE,
    FPGA_IRIG_OUT_TCG_CAL_MID,
    FPGA_IRIG_OUT_TCG_CAL_FINE_MSB,
    FPGA_IRIG_OUT_TCG_CAL_FINE_LSB,
    FPGA_IRIG_OUT_TIME_MSEC,
    FPGA_IRIG_OUT_TIME_SEC,
    FPGA_IRIG_OUT_TIME_MIN,
    FPGA_IRIG_OUT_TIME_HOUR,	/* 50 */
    FPGA_IRIG_OUT_TIME_DAY,
    FPGA_DISC_IN_STATE,
    FPGA_DISC_OUT_STATE,
    FPGA_LED_CONTROL_R_B,
    FPGA_LED_CONTROL_G,
    FPGA_LED_CONTROL_FLASH,
    FPGA_1588_TIME_MS,
    FPGA_1588_TIME_SEC,
    FPGA_1588_TIME_MIN,
    FPGA_1588_TIME_HOUR,	/* 60 */
    FPGA_1588_TIME_HDAY,
    FPGA_1588_TIME_DAY,
    FPGA_1588_TIME_YEAR,
    FPGA_EPE_PLL_CTRL_ADDR,
    FPGA_EPE_PLL_CTRL_RD,
    FPGA_EPE_PLL_CTRL_WR,
    FPGA_EPE_PLL_WR_DATA,
    FPGA_EPE_PLL_RD_DATA,
    FPGA_EPE_CH7_FRAME_SIZE,
    FPGA_EPE_HDLC_ENABLE,
    FPGA_EPE_HDLC_SEND_ADDR,
    FPGA_EPE_HDLC_CH7_MODE_MUX,
    FPGA_EPE_CH7_ENABLE,
    FPGA_EPE_HDLC_ADDR_BYTE,
    FPGA_EPE_HDLC_CTRL_BYTE,
    FPGA_EPE_CTRL_DEC_CH7_FRM_SZ,
    FPGA_EPE_CTRL_DEC_HDLC_ENABLE,
    FPGA_EPE_CTRL_DEC_CH7_ENABLE,
    FPGA_LED_CONTROL2_R,
    FPGA_LED_CONTROL2_B,
    FPGA_LED_CONTROL2_G,
    FPGA_LED_CONTROL2_FLASH,
    FPGA_LED_CONTROL2_MODE,


    FPGA_REGISTER_END
}vns_registers_t;

typedef struct vns_register_info_t{
	u32 regnum;
	u32 mask;
	u8 shift;
	u32 offset;
}vns_register_info;

extern const vns_register_info vns_reg_info[];

#endif /* REGISTERS_H_ */
