/*

 Vitesse Switch API software.

 Copyright (c) 2002-2012 Vitesse Semiconductor Corporation "Vitesse". All
 Rights Reserved.

 Unpublished rights reserved under the copyright laws of the United States of
 America, other countries and international treaties. Permission to use, copy,
 store and modify, the software and its source code is granted. Permission to
 integrate into other products, disclose, transmit and distribute the software
 in an absolute machine readable format (e.g. HEX file) is also granted.  The
 source code of the software may not be disclosed, transmitted or distributed
 without the written permission of Vitesse. The software and its source code
 may only be used in products utilizing the Vitesse switch products.

 This copyright notice must appear in any copy, modification, disclosure,
 transmission or distribution of the software. Vitesse retains all ownership,
 copyright, trade secret and proprietary rights in the software.

 THIS SOFTWARE HAS BEEN PROVIDED "AS IS," WITHOUT EXPRESS OR IMPLIED WARRANTY
 INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 FOR A PARTICULAR USE AND NON-INFRINGEMENT.

*/

#ifndef __ICFG_API_H__
#define __ICFG_API_H__

/**
 * \file
 * 
 * \brief ICFG API.
 * 
 * \details ICFG implements a library of functions for text-mode synthesis of
 * the currently running configuration. This configuration is expressed as
 * a structured and ordered set of ICLI-format command lines.
 *
 * A module with relevant configuration information must register itself with
 * ICFG at system startup-time. The module inserts a callback function pointer
 * to itself into the hard-coded synthesis order defined by enum
 * #vtss_icfg_ordering_t.
 *
 * Then, later, when synthesis is requested by the operator (through the GUI or
 * CLI), all callbacks are invoked in the correct order and with relevant
 * parameters (struct #vtss_icfg_query_request_t), allowing the callbacks to
 * generate appropriate output.
 *
 * This generation is done using a #printf-style function, #vtss_icfg_printf,
 * into a result data structure, #vtss_icfg_query_result_t. Client modules
 * should treat this data type as opaque. One call to the printf function may
 * freely generate several lines of output.
 *
 * Note that there is an upper limit to the amount of text that can be generated
 * in one call to #vtss_icfg_printf: #VTSS_ICFG_QUERY_RESULT_BLOCK_SIZE.
 *
 * NOTE WELL: Registration must be performed on all switches in a stack, but
 *            all query-related functions are only valid on the switch stack
 *            master. Do not call on slave switches or VTSS_RC_ERROR will be
 *            returned.
 *
 * Per-module Integration
 * ======================
 * For a module to integrate with ICLI, the following steps must be taken:
 *
 * 1. Determine where the module fits in the ordering, #vtss_icfg_ordering_t,
 *    and create new constants there. Observe the naming recommendations.
 *    Note that one module may appear several times in the ordering, but each
 *    time with a unique constant.
 *
 * 2. Create one or more callback functions with the prototype given by
 *    #vtss_icfg_query_func_t and, in the module's intialization, register them
 *    with ICFG using #vtss_icfg_query_register and the constants created in
 *    step 1.
 */

#include <vtss_types.h>
#include "icli_api.h"

/** \brief Comment lead-in.
 * 
 * \details Comments are one-lined with a specific lead-in character. Callbacks
 * are allowed to generate comment lines, but must do so very sparingly and
 * only in essential cases. As a rule, don't try to tell the system
 * administrator things he/she can reasonably be expected to know.
 */
#define VTSS_ICFG_COMMENT_LEADIN "!"



/** \brief ICFG Query Ordering.
 *
 * \details This enum orders the output generated by ICFG querying all
 * registered callbacks.
 *
 * Some of the enum values are reserved and used for grouping per ICLI command
 * submode; they are recognizable by the ...BEGIN and ..._END suffixes.
 *
 * IMPORTANT: All enum names should obey this naming convention:
 *
 *     VTSS_ICFG_module-name_command-identity
 *
 * The module-name is obvious, e.g. PORT or VLAN; the command-identity should
 * identify the command/set-of-commands generated here.
 *
 * For example, we could imagine an identifier like VTSS_ICFG_PORT_SPEED_DUPLEX
 * for the port module's synthesis of 'speed' and 'duplex' commands.
 *
 * Note how global config can be inserted between all submodes, if appropriate.
 *
 * Note: It is not allowed for multiple modules to use the same position in the
 * ordering. This so we avoid unexpected behavior depending on, say, runtime
 * module initialization order.
 */

typedef enum {
#ifdef VTSS_SW_OPTION_ICLI
    VTSS_ICFG_GLOBAL_ICLI,
#endif

#ifdef VTSS_SW_OPTION_USERS
    VTSS_ICFG_GLOBAL_USERS,
#endif

#ifdef VTSS_SW_OPTION_ACCESS_MGMT
    VTSS_ICFG_GLOBAL_ACCESS_MGMT,
#endif

    //------------------------- VLAN submode begin ----------------------------
    VTSS_ICFG_VLAN_BEGIN,
#if defined(VTSS_SW_OPTION_VLAN)
    VTSS_ICFG_VLAN_NAME_CONF,
#endif /* VTSS_SW_OPTION_VLAN */
    VTSS_ICFG_VLAN_END,
    //------------------------- VLAN submode end ------------------------------

#if defined(VTSS_SW_OPTION_IPMC_LIB)
    VTSS_ICFG_IPMC_LIB_IPMC_RANGE,

    //------------------------- IPMC submode begin ----------------------------
    VTSS_ICFG_IPMC_BEGIN,
    VTSS_ICFG_IPMC_LIB_PROFILE_DESC_RANGE,
    VTSS_ICFG_IPMC_END,
    //------------------------- IPMC submode end ------------------------------

    VTSS_ICFG_IPMC_LIB_IPMC_PROFILE_CTRL,
#endif /* VTSS_SW_OPTION_IPMC_LIB */

#if defined(VTSS_SW_OPTION_SNMP)
    //------------------------- SNMP server host submode begin ----------------
    VTSS_ICFG_SNMPSERVER_HOST_BEGIN,
    VTSS_ICFG_TRAP_HOST_CONF,
    VTSS_ICFG_SNMPSERVER_HOST_END,
    //------------------------- SNMP server host submode end ------------------
#endif /* VTSS_SW_OPTION_SNMP */

#ifdef VTSS_SW_OPTION_IPV6
    VTSS_ICFG_IPV6_GLOBAL,
#endif /* VTSS_SW_OPTION_IPV6 */

#ifdef VTSS_SW_OPTION_DNS
    VTSS_ICFG_IP_DNS_CONF,
#endif /* VTSS_SW_OPTION_DNS */

#if defined(VTSS_SW_OPTION_MVR)
    VTSS_ICFG_IPMC_MVR_INTF,
#endif /* VTSS_SW_OPTION_MVR */

#if defined(VTSS_SW_OPTION_IPMC)
    VTSS_ICFG_IPMC_SNP_IGMP,
#if defined(VTSS_SW_OPTION_SMB_IPMC)
    VTSS_ICFG_IPMC_SNP_MLD,
#endif /* VTSS_SW_OPTION_SMB_IPMC */
#endif /* VTSS_SW_OPTION_IPMC */

#if defined(VTSS_SW_OPTION_VLAN)
    VTSS_ICFG_VLAN_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_VLAN */

#if defined(VTSS_SW_OPTION_VCL)
    VTSS_ICFG_VCL_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_VCL */

#if defined(VTSS_SW_OPTION_DHCP_SNOOPING)
    VTSS_ICFG_DHCP_SNOOPING_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_DHCP_SNOOPING */

#if defined(VTSS_SW_OPTION_DHCP_RELAY)
    VTSS_ICFG_DHCP_RELAY_CONFIG,
#endif /* VTSS_SW_OPTION_DHCP_RELAY */

#if defined(VTSS_SW_OPTION_ARP_INSPECTION)
    VTSS_ICFG_ARP_INSPECTION_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_ARP_INSPECTION */
#if defined(VTSS_SW_OPTION_IP_SOURCE_GUARD)
    VTSS_ICFG_IP_SOURCE_GUARD_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_IP_SOURCE_GUARD */
#if defined(VTSS_SW_OPTION_NTP)
    VTSS_ICFG_VTSS_NTP_GLOBAL_CONF,
#else
	VTSS_ICFG_VTSS_SNTP_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_NTP */
#if defined(VTSS_SW_OPTION_DAYLIGHT_SAVING)
    VTSS_ICFG_DAYLIGHT_SAVING_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_DAYLIGHT_SAVING */

#if defined(VTSS_SW_OPTION_HTTPS)
    VTSS_HTTPS_ICFG_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_HTTPS */

#if defined(VTSS_SW_OPTION_SSH)
    VTSS_SSH_ICFG_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_SSH */

#if defined(VTSS_SW_OPTION_MIRROR)
    VTSS_ICFG_MIRROR_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_MIRROR */

#if defined(VTSS_SW_OPTION_MAC)
    VTSS_ICFG_MAC_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_MAC */

#if defined(VTSS_SW_OPTION_AGGR)
    VTSS_ICFG_AGGR_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_AGGR */

#if defined(VTSS_SW_OPTION_LACP)
    VTSS_ICFG_LACP_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_LACP */

#if defined(VTSS_SW_OPTION_EEE)
    VTSS_ICFG_EEE_GLOBAL_CONF,
#endif // VTSS_SW_OPTION_EEE

#if defined(VTSS_SW_OPTION_FAN)
    VTSS_ICFG_FAN_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_FAN */

#if defined(VTSS_SW_OPTION_LED_POW_REDUC)
    VTSS_ICFG_LED_POW_REDUC_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_LED_POW_REDUC */

#if defined(VTSS_SW_OPTION_LLDP)
    VTSS_ICFG_LLDP_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_LLDP */

#if defined(VTSS_SW_OPTION_LLDP_MED)
    VTSS_ICFG_LLDPMED_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_LLDP_MED */

#if defined(VTSS_SW_OPTION_POE)
    VTSS_ICFG_POE_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_POE*/

#if defined(VTSS_SW_OPTION_THERMAL_PROTECT)
    VTSS_ICFG_THERMAL_PROTECT_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_THERMAL_PROTECT */

#if defined(VTSS_SW_OPTION_SNMP)
    VTSS_ICFG_SNMP_GLOBAL_CONF,
    VTSS_ICFG_TRAP_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_SNMP */

#if defined(VTSS_SW_OPTION_SYSLOG)
    VTSS_ICFG_SYSLOG_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_SYSLOG */

#if defined(VTSS_SW_OPTION_AUTH)
    VTSS_ICFG_AUTH_AGENT_CONF,
    VTSS_ICFG_AUTH_RADIUS_CONF,
    VTSS_ICFG_AUTH_TACACS_CONF,
#endif /* VTSS_SW_OPTION_AUTH */

#if defined(VTSS_SW_OPTION_UPNP)
    VTSS_ICFG_UPNP_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_UPNP */

#if defined(VTSS_SW_OPTION_QOS)
    VTSS_ICFG_QOS_GLOBAL_CONF,
    VTSS_ICFG_QOS_QCE_CONF,
#endif /* VTSS_SW_OPTION_QOS */

#if defined(VTSS_SW_OPTION_ACL)
    VTSS_ICFG_ACL_GLOBAL_CONF,
#endif /* VTSS_SW_OPTION_ACL */

#ifdef VTSS_SW_OPTION_VOICE_VLAN
    VTSS_ICFG_GLOBAL_VOICE_VLAN,
#endif

    //------------------------- Interface Ethernet submode begin --------------
    VTSS_ICFG_INTERFACE_ETHERNET_BEGIN,

#ifdef VTSS_SW_OPTION_VOICE_VLAN
    VTSS_ICFG_INTERFACE_ETHERNET_VOICE_VLAN,
#endif

#if defined(VTSS_SW_OPTION_VLAN)
    VTSS_ICFG_VLAN_PORT_CONF,
#endif /* VTSS_SW_OPTION_VLAN */

#if defined(VTSS_SW_OPTION_VCL)
    VTSS_ICFG_VCL_PORT_CONF,
#endif /* VTSS_SW_OPTION_VCL */

#if defined(VTSS_SW_OPTION_PVLAN)
    VTSS_ICFG_PVLAN_PORT_CONF,
#endif /* VTSS_SW_OPTION_VLAN */

#if defined(VTSS_SW_OPTION_MVR)
    VTSS_ICFG_IPMC_MVR_PORT,
#endif /* VTSS_SW_OPTION_MVR */

#if defined(VTSS_SW_OPTION_IPMC)
    VTSS_ICFG_IPMC_SNP_IGMP_PORT,
#if defined(VTSS_SW_OPTION_SMB_IPMC)
    VTSS_ICFG_IPMC_SNP_MLD_PORT,
#endif /* VTSS_SW_OPTION_SMB_IPMC */
#endif /* VTSS_SW_OPTION_IPMC */

#if defined(VTSS_SW_OPTION_DHCP_SNOOPING)
    VTSS_ICFG_DHCP_SNOOPING_PORT_CONF,
#endif /* VTSS_SW_OPTION_DHCP_SNOOPING */

#if defined(VTSS_SW_OPTION_ARP_INSPECTION)
    VTSS_ICFG_ARP_INSPECTION_PORT_CONF,
#endif /* VTSS_SW_OPTION_ARP_INSPECTION */
#if defined(VTSS_SW_OPTION_IP_SOURCE_GUARD)
    VTSS_ICFG_IP_SOURCE_GUARD_PORT_CONF,
#endif /* VTSS_SW_OPTION_IP_SOURCE_GUARD */
#ifdef VTSS_SW_OPTION_RMON
    VTSS_ICFG_INTERFACE_ETHERNET_RMON,
#endif
#if defined(VTSS_SW_OPTION_LLDP)
    VTSS_ICFG_LLDP_PORT_CONF,
#endif /* VTSS_SW_OPTION_LLDP */

#if defined(VTSS_SW_OPTION_LLDP_MED)
    VTSS_ICFG_LLDPMED_PORT_CONF,
#endif /* VTSS_SW_OPTION_LLDP_MED */

#if defined(VTSS_SW_OPTION_POE)
    VTSS_ICFG_POE_PORT_CONF,
#endif /* VTSS_SW_OPTION_POE */

#if defined(VTSS_SW_OPTION_QOS)
    VTSS_ICFG_QOS_PORT_CONF,
#endif /* VTSS_SW_OPTION_QOS */

#if defined(VTSS_SW_OPTION_ACL)
    VTSS_ICFG_ACL_PORT_CONF,
#endif /* VTSS_SW_OPTION_ACL */

#if defined(VTSS_SW_OPTION_THERMAL_PROTECT)
    VTSS_ICFG_THERMAL_PROTECT_PORT_CONF,
#endif /* VTSS_SW_OPTION_THERMAL_PROTECT */

#if defined(VTSS_SW_OPTION_EEE)
    VTSS_ICFG_EEE_PORT_CONF,
#endif // VTSS_SW_OPTION_EEE


#if VTSS_SW_OPTION_PHY_POWER_CONTROL
    VTSS_ICFG_PHY_POWER_CONTROL_PORT_CONF,
#endif // VTSS_SW_OPTION_PHY_POWER_CONTROL

#if defined(VTSS_SW_OPTION_MAC)
    VTSS_ICFG_MAC_INTERFACE_CONF,
#endif /* VTSS_SW_OPTION_MAC */

#if defined(VTSS_SW_OPTION_AGGR)
    VTSS_ICFG_AGGR_INTERFACE_CONF,
#endif /* VTSS_SW_OPTION_AGGR */

#if defined(VTSS_SW_OPTION_LACP)
    VTSS_ICFG_LACP_INTERFACE_CONF,
#endif /* VTSS_SW_OPTION_LACP */

#if defined(VTSS_SW_OPTION_SNMP)
    VTSS_ICFG_TRAP_PORT_CONF,
#endif /* VTSS_SW_OPTION_SNMP */

    VTSS_ICFG_INTERFACE_ETHERNET_END,
    //------------------------- Interface Ethernet submode end ----------------

    //------------------------- Interface VLAN submode begin ------------------
    VTSS_ICFG_INTERFACE_VLAN_BEGIN,

#ifdef VTSS_SW_OPTION_IPV6
    VTSS_ICFG_IPV6_INTERFACE,
#endif /* VTSS_SW_OPTION_IPV6 */

#if defined(VTSS_SW_OPTION_IPMC)
    VTSS_ICFG_IPMC_SNP_IGMP_INTF,
#if defined(VTSS_SW_OPTION_SMB_IPMC)
    VTSS_ICFG_IPMC_SNP_MLD_INTF,
#endif /* VTSS_SW_OPTION_SMB_IPMC */
#endif /* VTSS_SW_OPTION_IPMC */

    VTSS_ICFG_INTERFACE_VLAN_END,
    //------------------------- Interface VLAN submode end --------------------

    //------------------------- STP aggregation submode begin -----------------
    VTSS_ICFG_STP_AGGR_BEGIN,
    VTSS_ICFG_STP_AGGR_END,
    //------------------------- STP aggregation submode end -------------------

#if defined(VTSS_SW_OPTION_MVR)
    VTSS_ICFG_IPMC_MVR_GLOBAL,
#endif /* VTSS_SW_OPTION_MVR */

#if defined(VTSS_SW_OPTION_IPMC)
    VTSS_ICFG_IPMC_SNP_IGMP_CTRL,
#if defined(VTSS_SW_OPTION_SMB_IPMC)
    VTSS_ICFG_IPMC_SNP_MLD_CTRL,
#endif /* VTSS_SW_OPTION_SMB_IPMC */
#endif /* VTSS_SW_OPTION_IPMC */

#ifdef VTSS_SW_OPTION_RMON
    VTSS_ICFG_GLOBAL_RMON,
#endif

    //------------------------- Line submode begin ----------------------------
    VTSS_ICFG_LINE_BEGIN,
#ifdef VTSS_SW_OPTION_ICLI
    VTSS_ICFG_LINE_ICLI,
#endif
    VTSS_ICFG_LINE_END,
    //------------------------- Line submode end ------------------------------

    VTSS_ICFG_LAST
} vtss_icfg_ordering_t;



/** \section Query Result API.
 *
 * \details These data structures and functions are used during synthesis of
 * configuration.
 *
 * The #vtss_icfg_query_result_t result structure is made up of a linked list
 * of #vtss_icfg_query_result_buf_t blocks of output. A new block is allocated
 * when the current (pointed to by #tail) runs out of capacity. NOTE that
 * a block may not be filled completely; observe #used. This also holds for
 * non-tail blocks, and is caused by the way printf is implemented.
 */

/** \brief One data block; linked list. text[] is always zero-terminated. */
typedef struct _vtss_icfg_query_result_buf_t {
    u32                                  used;    /* Number of chars used; index of next free char */
    u32                                  size;    /* Number of chars allocated for #text[] */
    struct _vtss_icfg_query_result_buf_t *next;   /* NULL == this is tail */
    char                                 text[0]; /* Text here; size is variable */
} vtss_icfg_query_result_buf_t;

/** \brief The query result data structure. Linked list.
 */
typedef struct {
    vtss_icfg_query_result_buf_t *head;   /* First buf filled in */
    vtss_icfg_query_result_buf_t *tail;   /* Current buf being filled in */
} vtss_icfg_query_result_t;

/** \brief Initialize a query result data structure.
 *
 * \details Only valid on stack master.
 *
 * \param initial_size [IN]     Size of first block. Zero == default value
 * \param res          [IN/OUT] The result data structure
 *
 * \return VTSS_RC_OK on success; VTSS_RC_ERROR on memory allocation problems.
 */
vtss_rc vtss_icfg_init_query_result(u32 initial_size,
                                    vtss_icfg_query_result_t *res);

/** \brief Free all memory allocated by a query result data structure.
 * The structure is invalid after the call and must be re-initialized before
 * any further use.
 * \details Only valid on stack master.
 * \param res [IN/OUT] The result data structure.
 */
void vtss_icfg_free_query_result(vtss_icfg_query_result_t *res);

/** \brief printf into a result data structure.
 * \details Only valid on stack master.
 * \param res    [IN/OUT] The result data structure.
 * \param format [IN]     printf-style format string.
 * \return VTSS_RC_OK on success; VTSS_RC_ERROR on memory allocation problems.
 */
vtss_rc vtss_icfg_printf(vtss_icfg_query_result_t *res, const char *format,
                         ...);



/** \section Query Request API.
 *
 * \details A module wanting to synthesize configuration must create one or
 * more callback functions which are then invoked by the ICFG core. The callback
 * function is provided with parameters that identify which ICLI mode that's
 * being processed at the moment plus mode-specific instance parameters.
 * Also, a result buffer structure is passed for filling in.
 *
 * For items in global config, the callback is only invoked once. For sub-modes
 * (e.g. interfaces or VLANs) the callback is invoked once per interface or
 * VLAN instance.
 */

typedef struct {
    icli_cmd_mode_t      cmd_mode;          /* ICLI command mode */
    vtss_icfg_ordering_t order;             /* Order */
    BOOL                 all_defaults;      /* TRUE == generate commands and parameters for default settings too. FALSE == only non-default */
    union {
        icli_switch_port_range_t port;      /* Not used for ranges, only single ports (port.port_cnt is always 1) */
        u32                      vlan;
        u32                      line;
        char                     string[64];
    } instance_id;                          /* Instance identification */
} vtss_icfg_query_request_t;

/** \brief Callback signature.
 * \param req    [IN]     Request data.
 * \param result [IN/OUT] Result data. Treat as opaque.
 * \return Return value. VTSS_RC_ERROR on memory/parameter errors.
 */
typedef vtss_rc (*vtss_icfg_query_func_t)(const vtss_icfg_query_request_t *req,
                                          vtss_icfg_query_result_t *result);

/** \brief Query all modules and return the result.
 * 
 * \details Only valid on stack master.
 *
 * Note: User must call #vtss_icfg_query_result_free(result) when done with the
 * results.
 *
 * \param all_defaults [IN]     TRUE: Callbacks should include all default
 *                              values
 * \param result       [IN/OUT] Result data. NOTE: #vtss_icfg_init_query_result
 *                              will be called by this function, so don't do it
 *                              in advance or memory will leak.
 */
vtss_rc vtss_icfg_query_all(BOOL                     all_defaults,
                            vtss_icfg_query_result_t *result);

/** \brief Query all modules for something specific and return the result.
 *
 * \details Only valid on stack master.
 *
 * Note: User must call #vtss_icfg_init_query_result(..., result) prior to
 * calling this function.
 *
 * Note: User must call #vtss_icfg_query_result_free(result) when done with the
 * results.
 *
 * \param req    [IN/OUT] Request. Note: req.order is ignored and overwritten.
 * \param result [IN/OUT] Result data. NOTE: #vtss_icfg_init_query_result will
 * be called by this function, so don't do it in advance or memory will leak.
 */
vtss_rc vtss_icfg_query_specific(vtss_icfg_query_request_t *req,
                                 vtss_icfg_query_result_t  *result);



/** \section Query Registration API.
 */


/** \brief Register callback at a particular position in the order.
 *
 * \details Valid on all switches in a stack.
 *
 * \param global_order [IN]   Where in the ordering to insert the #query_cb
 * \param query_cb     [IN]   Callback.
 *
 * \return Result code. VTSS_RC_ERROR if insert failed (already used, bad
 * index).
 */
vtss_rc vtss_icfg_query_register(vtss_icfg_ordering_t   global_order,
                                 vtss_icfg_query_func_t query_cb);



/** \section Utilities.
 */

/** \brief Structure for the elements that make up a URL of the form:
 *
 *      protocol://host[:port]/path
 *
 * e.g.
 *
 *      tftp://1.2.3.4:5678/path/to/myfile.dat
 *
 */
typedef struct {
    char protocol[32];
    char host[64];
    u16  port;         /* Port number, or zero if none given */
    char path[256];
} vtss_icfg_url_parts_t;



/** \brief Initialize #vtss_icfg_url_parts_t to defaults (empty strings, port zero)
 *
 * \param parts [IN/OUT] The initialized struct
 */
void vtss_icfg_init_url_parts_t(vtss_icfg_url_parts_t *parts);



/** \brief Decompose URL string by scanning #url.
 *
 * \param url   [IN]  Pointer to string
 * \param parts [OUT] The decomposed URL
 *
 * \return TRUE = decomposition is valid; FALSE = error in URL
 */
BOOL vtss_icfg_decompose_url(const char *url, vtss_icfg_url_parts_t *parts);



/** \brief Compose URL into pre-allocated buffer of given max length.
 *
 * \param url      [IN/OUT] Destination buffer
 * \param max_len  [IN]     Max length of buffer, including terminating \0
 * \param parts    [IN]     URL parts
 *
 * \return TRUE = composition is valid; FALSE = result too long or #parts invalid
 */

BOOL vtss_icfg_compose_url(char *url, int max_len, const vtss_icfg_url_parts_t *parts);



/** \section Initialization.
 */

/** \brief Initialize the ICFG module.
 *
 * \param data [IN] The initialization struct.
 */
vtss_rc icfg_init(vtss_init_data_t *data);



/** \section Load/Save mutex.
 *
 * \details This mutex is used for protecting whole-file load/save operations:
 *          Max one can be in progress at any time; overlapping requests must
 *          be denied with an error message
 */

/** \brief Try to lock the mutex.
 *
 * \return TRUE == obtained lock; FALSE == already locked, can't load/save now
 */
BOOL vtss_icfg_try_lock_io_mutex(void);

/** \brief Unlock the mutex.
 */
void vtss_icfg_unlock_io_mutex(void);



#endif	/* __ICFG_API_H__ */
